// Marks every tenant-scoped entity with Application.Core.Interfaces.ITenantScoped.
// Hand-authored and kept OUTSIDE Entities/ so an EF Power Tools re-scaffold cannot wipe it.
// Regenerate the list: grep -l "public Guid TenantId { get; set; }" Application.Core/Entities/*.cs
using Application.Core.Interfaces;

namespace Application.Core.Entities;

public partial class Account : ITenantSharable { } // ITenantSharable : ITenantScoped — the standard CoA skeleton is shared
public partial class AccountType : ITenantScoped { }
public partial class Area : ITenantScoped { }
public partial class BankAccount : ITenantScoped { }
public partial class BillOfMaterial : ITenantScoped { }
public partial class BillOfMaterialDetail : ITenantScoped { }
public partial class Category : ITenantScoped { }
public partial class Company : ITenantScoped { }
public partial class CostCenter : ITenantScoped { }
public partial class Country : ITenantScoped { }
public partial class Currency : ITenantScoped { }
public partial class CustomerWiseProductDiscount : ITenantScoped { }
public partial class CustomerWiseProductDiscountDetail : ITenantScoped { }
public partial class CustomerWiseProductDiscountUsageHistory : ITenantScoped { }
public partial class DeliveryNote : ITenantScoped { }
public partial class DeliveryNoteDetail : ITenantScoped { }
public partial class DeliveryPlace : ITenantScoped { }
public partial class Department : ITenantScoped { }
public partial class Designation : ITenantScoped { }
public partial class DiscountProductWise : ITenantScoped { }
public partial class DiscountProductWiseDetail : ITenantScoped { }
public partial class DiscountProductWiseUsageHistory : ITenantScoped { }
public partial class EmailAccount : ITenantScoped { }
public partial class Employee : ITenantScoped { }
public partial class EventLog : ITenantScoped { }
public partial class FinancialYear : ITenantScoped { }
public partial class FundTransfer : ITenantScoped { }
public partial class FundTransferTransactionType : ITenantScoped { }
public partial class Generic : ITenantScoped { }
public partial class GoodsReceiveNote : ITenantScoped { }
public partial class GoodsReceiveNoteDetail : ITenantScoped { }
public partial class InventoryType : ITenantScoped { }
public partial class JobLocation : ITenantScoped { }
public partial class JournalEntry : ITenantScoped { }
public partial class JournalEntryDetail : ITenantScoped { }
public partial class LcAdjustment : ITenantScoped { }
public partial class LcAdjustmentDetail : ITenantScoped { }
public partial class LccostEntry : ITenantScoped { }
public partial class LccostEntryDetail : ITenantScoped { }
public partial class Machine : ITenantScoped { }
public partial class Manufacturer : ITenantScoped { }
public partial class ManufacturingOrder : ITenantScoped { }
public partial class ManufacturingOrderDetail : ITenantScoped { }
public partial class MeasurementUnit : ITenantScoped { }
public partial class Notification : ITenantScoped { }
public partial class PackSize : ITenantScoped { }
public partial class PaymentMethod : ITenantScoped { }
public partial class PaymentMode : ITenantScoped { }
public partial class PaymentVoucher : ITenantScoped { }
public partial class PaymentVoucherDetail : ITenantScoped { }
public partial class Picture : ITenantScoped { }
public partial class PoPriceAdjustmentAfterGrn : ITenantScoped { }
public partial class PoPriceAdjustmentAfterGrnDetail : ITenantScoped { }
public partial class Product : ITenantScoped { }
public partial class ProductAudit : ITenantScoped { }
public partial class ProductCostSetup : ITenantScoped { }
public partial class ProductType : ITenantScoped { }
public partial class Production : ITenantScoped { }
public partial class ProductionDetail : ITenantScoped { }
public partial class PurchaseInvoice : ITenantScoped { }
public partial class PurchaseInvoiceDetail : ITenantScoped { }
public partial class PurchaseInvoiceSupplierPaymentMapping : ITenantScoped { }
public partial class PurchaseOrder : ITenantScoped { }
public partial class PurchaseOrderDetail : ITenantScoped { }
public partial class PurchaseRequisition : ITenantScoped { }
public partial class PurchaseRequisitionDetail : ITenantScoped { }
public partial class PurchaseRequisitionPurchaseOrderMapping : ITenantScoped { }
public partial class PurchaseReturn : ITenantScoped { }
public partial class PurchaseReturnDetail : ITenantScoped { }
public partial class ReceivePayment : ITenantScoped { }
public partial class ReceivePaymentAgainstSale : ITenantScoped { }
public partial class ReceivePaymentAgainstSaleSaleInvoiceMapping : ITenantScoped { }
public partial class ReceivePaymentDetail : ITenantScoped { }
public partial class ReceivePaymentPictureMapping : ITenantScoped { }
public partial class ReceiveVoucher : ITenantScoped { }
public partial class ReceiveVoucherDetail : ITenantScoped { }
public partial class RefreshToken : ITenantScoped { }
public partial class Region : ITenantScoped { }
public partial class RfqSent : ITenantScoped { }
public partial class Role : ITenantScoped { }
public partial class RoleClaim : ITenantScoped { }
public partial class SaleInvoice : ITenantScoped { }
public partial class SaleInvoiceDetail : ITenantScoped { }
public partial class SaleOrder : ITenantScoped { }
public partial class SaleOrderDetail : ITenantScoped { }
public partial class SaleQuotation : ITenantScoped { }
public partial class SaleQuotationDetail : ITenantScoped { }
public partial class SaleReturn : ITenantScoped { }
public partial class SaleReturnDetail : ITenantScoped { }
public partial class Shift : ITenantScoped { }
public partial class Stock : ITenantScoped { }
public partial class StockAdjustment : ITenantScoped { }
public partial class StockAdjustmentDetail : ITenantScoped { }
public partial class StockTransfer : ITenantScoped { }
public partial class StockTransferDetail : ITenantScoped { }
public partial class Store : ITenantScoped { }
public partial class SupplierPayment : ITenantScoped { }
public partial class SupplierPaymentAgainstPurchase : ITenantScoped { }
public partial class SupplierPaymentDetail : ITenantScoped { }
public partial class SupplierProductMapping : ITenantScoped { }
public partial class SupplierTransactionAgainstPo : ITenantScoped { }
public partial class Territory : ITenantScoped { }
public partial class Transaction : ITenantScoped { }
public partial class User : ITenantScoped { }
public partial class VendorQuotation : ITenantScoped { }
public partial class VendorQuotationDetail : ITenantScoped { }
public partial class VoucherEntry : ITenantScoped { }
public partial class VoucherEntryDetail : ITenantScoped { }
public partial class Zone : ITenantScoped { }
