// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Application.Core.Data;
using Application.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Application.Core.Data.Configurations
{
    public partial class AccountConfiguration : IEntityTypeConfiguration<Account>
    {
        public void Configure(EntityTypeBuilder<Account> entity)
        {
            entity.ToTable("Account");

            // Code is unique per tenant (the shared CoA skeleton carries the
            // SystemTenantId, so its fixed codes don't clash with any tenant's).
            entity.HasIndex(e => new { e.TenantId, e.Code }, "UQ_Account_Code").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Address).HasMaxLength(100);
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ContactNo).HasMaxLength(100);
            entity.Property(e => e.ContactPersonContactNo).HasMaxLength(200);
            entity.Property(e => e.ContactPersonDesignation).HasMaxLength(200);
            entity.Property(e => e.ContactPersonEmail).HasMaxLength(200);
            entity.Property(e => e.ContactPersonName).HasMaxLength(200);
            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.CustomerCreditDays)
                .HasMaxLength(500)
                .HasDefaultValueSql("((0))");
            entity.Property(e => e.CustomerCreditLimit).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CustomerTargetQuantity)
                .HasMaxLength(500)
                .HasDefaultValueSql("((0))");
            entity.Property(e => e.Email).HasMaxLength(100);
            entity.Property(e => e.Name).IsRequired();
            entity.Property(e => e.NationalId).HasMaxLength(100);
            entity.Property(e => e.OwnersName).HasMaxLength(200);
            entity.Property(e => e.TradeLicense).HasMaxLength(200);
            entity.Property(e => e.UpdatedBy).HasMaxLength(100);

            entity.HasOne(d => d.AccountType).WithMany(p => p.Accounts)
                .HasForeignKey(d => d.AccountTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Account_AccountType");

            entity.HasOne(d => d.CustomerMarketingOfficer).WithMany(p => p.Accounts)
                .HasForeignKey(d => d.CustomerMarketingOfficerId)
                .HasConstraintName("FK_MarketingOfficer_Employee");

            entity.HasOne(d => d.Parent).WithMany(p => p.InverseParent)
                .HasForeignKey(d => d.ParentId)
                .HasConstraintName("FK_AccountChild_AccountParent");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Account> entity);
    }
}
