// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Application.Core.Data;
using Application.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Application.Core.Data.Configurations
{
    public partial class BankAccountConfiguration : IEntityTypeConfiguration<BankAccount>
    {
        public void Configure(EntityTypeBuilder<BankAccount> entity)
        {
            entity.ToTable("BankAccount");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.AccNo)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.BankName)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.BranchName)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.RoutingNo).HasMaxLength(200);
            entity.Property(e => e.UpdatedBy).HasMaxLength(100);

            entity.HasOne(d => d.Account).WithMany(p => p.BankAccounts)
                .HasForeignKey(d => d.AccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BankAccount_Account");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<BankAccount> entity);
    }
}
