// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Application.Core.Data;
using Application.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Application.Core.Data.Configurations
{
    public partial class BillOfMaterialDetailConfiguration : IEntityTypeConfiguration<BillOfMaterialDetail>
    {
        public void Configure(EntityTypeBuilder<BillOfMaterialDetail> entity)
        {
            entity.ToTable("BillOfMaterialDetail");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.Percentage).HasColumnType("decimal(18, 10)");
            entity.Property(e => e.Quantity).HasColumnType("decimal(18, 3)");
            entity.Property(e => e.UpdatedBy).HasMaxLength(100);

            entity.HasOne(d => d.BillOfMaterial).WithMany(p => p.BillOfMaterialDetails)
                .HasForeignKey(d => d.BillOfMaterialId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BillOfMaterialDetail_BillOfMaterial");

            entity.HasOne(d => d.RawMaterial).WithMany(p => p.BillOfMaterialDetails)
                .HasForeignKey(d => d.RawMaterialId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BillOfMaterialDetail_RawMaterial");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<BillOfMaterialDetail> entity);
    }
}
