// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Application.Core.Data;
using Application.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Application.Core.Data.Configurations
{
    public partial class CustomerWiseProductDiscountDetailConfiguration : IEntityTypeConfiguration<CustomerWiseProductDiscountDetail>
    {
        public void Configure(EntityTypeBuilder<CustomerWiseProductDiscountDetail> entity)
        {
            entity.ToTable("CustomerWiseProductDiscountDetail");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CashDiscount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.InvoiceDiscount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.MonthlyDiscount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.SalePrice).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.SpecialDiscount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TargetDiscount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.UpdatedBy).HasMaxLength(100);
            entity.Property(e => e.YearlyDiscount).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.CustomerWiseProductDiscount).WithMany(p => p.CustomerWiseProductDiscountDetails)
                .HasForeignKey(d => d.CustomerWiseProductDiscountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CustomerWiseProductDiscountDetail_CustomerWiseProductDiscount");

            entity.HasOne(d => d.Product).WithMany(p => p.CustomerWiseProductDiscountDetails)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CustomerWiseProductDiscountDetail_Product");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CustomerWiseProductDiscountDetail> entity);
    }
}
