// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Application.Core.Data;
using Application.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Application.Core.Data.Configurations
{
    public partial class CustomerWiseProductDiscountUsageHistoryConfiguration : IEntityTypeConfiguration<CustomerWiseProductDiscountUsageHistory>
    {
        public void Configure(EntityTypeBuilder<CustomerWiseProductDiscountUsageHistory> entity)
        {
            entity.ToTable("CustomerWiseProductDiscountUsageHistory");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.UpdatedBy).HasMaxLength(100);

            entity.HasOne(d => d.CustomerWiseProductDiscount).WithMany(p => p.CustomerWiseProductDiscountUsageHistories)
                .HasForeignKey(d => d.CustomerWiseProductDiscountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CustomerWiseProductDiscountUsageHistory_CustomerWiseProductDiscount");

            entity.HasOne(d => d.SaleOrder).WithMany(p => p.CustomerWiseProductDiscountUsageHistories)
                .HasForeignKey(d => d.SaleOrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CustomerWiseProductDiscountUsageHistory_SaleOrder");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CustomerWiseProductDiscountUsageHistory> entity);
    }
}
