// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Application.Core.Data;
using Application.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Application.Core.Data.Configurations
{
    public partial class DeliveryNoteConfiguration : IEntityTypeConfiguration<DeliveryNote>
    {
        public void Configure(EntityTypeBuilder<DeliveryNote> entity)
        {
            entity.ToTable("DeliveryNote");

            entity.HasIndex(e => e.DeliveryNoteNo, "UQ_DeliveryNoteNo").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.ApprovedBy).HasMaxLength(100);
            entity.Property(e => e.CheckedBy).HasMaxLength(100);
            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.CreditLimit).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.DeliveryNoteNo)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.DepoCharge).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Discount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.DriverContactNo).HasMaxLength(20);
            entity.Property(e => e.DriverName).HasMaxLength(500);
            entity.Property(e => e.LimitAvailed).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.NetTotal).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.OfferDiscount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.OtherDiscount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.ReferenceNo).HasMaxLength(100);
            entity.Property(e => e.SaleOrderNo)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Subtotal).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Total).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TransportationCost).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TruckNo).HasMaxLength(100);
            entity.Property(e => e.UnpostedBy).HasMaxLength(100);
            entity.Property(e => e.UpdatedBy).HasMaxLength(100);

            entity.HasOne(d => d.Customer).WithMany(p => p.DeliveryNotes)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DeliveryNote_Customer");

            entity.HasOne(d => d.Store).WithMany(p => p.DeliveryNotes)
                .HasForeignKey(d => d.StoreId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DeliveryNote_Store");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<DeliveryNote> entity);
    }
}
