// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Application.Core.Data;
using Application.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Application.Core.Data.Configurations
{
    public partial class DiscountProductWiseDetailConfiguration : IEntityTypeConfiguration<DiscountProductWiseDetail>
    {
        public void Configure(EntityTypeBuilder<DiscountProductWiseDetail> entity)
        {
            entity.ToTable("DiscountProductWiseDetail");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.DiscountAmountPerKg).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.UpdatedBy).HasMaxLength(100);

            entity.HasOne(d => d.DiscountProductWise).WithMany(p => p.DiscountProductWiseDetails)
                .HasForeignKey(d => d.DiscountProductWiseId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DiscountProductWiseDetail_DiscountProductWise");

            entity.HasOne(d => d.Product).WithMany(p => p.DiscountProductWiseDetails)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DiscountProductWiseDetail_Product");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<DiscountProductWiseDetail> entity);
    }
}
