// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Application.Core.Data;
using Application.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Application.Core.Data.Configurations
{
    public partial class DiscountProductWiseUsageHistoryConfiguration : IEntityTypeConfiguration<DiscountProductWiseUsageHistory>
    {
        public void Configure(EntityTypeBuilder<DiscountProductWiseUsageHistory> entity)
        {
            entity.ToTable("DiscountProductWiseUsageHistory");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.UpdatedBy).HasMaxLength(100);

            entity.HasOne(d => d.DiscountProductWise).WithMany(p => p.DiscountProductWiseUsageHistories)
                .HasForeignKey(d => d.DiscountProductWiseId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DiscountProductWiseUsageHistory_DiscountProductWise");

            entity.HasOne(d => d.SaleOrder).WithMany(p => p.DiscountProductWiseUsageHistories)
                .HasForeignKey(d => d.SaleOrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DiscountProductWiseUsageHistory_SaleOrder");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<DiscountProductWiseUsageHistory> entity);
    }
}
