// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Application.Core.Data;
using Application.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Application.Core.Data.Configurations
{
    public partial class EmailAccountConfiguration : IEntityTypeConfiguration<EmailAccount>
    {
        public void Configure(EntityTypeBuilder<EmailAccount> entity)
        {
            entity.ToTable("EmailAccount");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.DisplayName)
                .HasMaxLength(255)
                .UseCollation("Latin1_General_CI_AS");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(255)
                .UseCollation("Latin1_General_CI_AS");
            entity.Property(e => e.Host)
                .IsRequired()
                .HasMaxLength(255)
                .UseCollation("Latin1_General_CI_AS");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(255)
                .UseCollation("Latin1_General_CI_AS");
            entity.Property(e => e.UpdatedBy).HasMaxLength(100);
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(255)
                .UseCollation("Latin1_General_CI_AS");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EmailAccount> entity);
    }
}
