// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Application.Core.Data;
using Application.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Application.Core.Data.Configurations
{
    public partial class FundTransferConfiguration : IEntityTypeConfiguration<FundTransfer>
    {
        public void Configure(EntityTypeBuilder<FundTransfer> entity)
        {
            entity.ToTable("FundTransfer");

            entity.HasIndex(e => e.FundTransferNo, "UQ_FundTransferNo").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.ApprovedBy).HasMaxLength(100);
            entity.Property(e => e.Charges).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CheckedBy).HasMaxLength(100);
            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.FundTransferNo)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.UpdatedBy).HasMaxLength(100);

            entity.HasOne(d => d.CostCenter).WithMany(p => p.FundTransfers)
                .HasForeignKey(d => d.CostCenterId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FundTransfer_CostCenter");

            entity.HasOne(d => d.FundTransferTransactionType).WithMany(p => p.FundTransfers)
                .HasForeignKey(d => d.FundTransferTransactionTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FundTransfer_FundTransferTransactionType");

            entity.HasOne(d => d.TransferFromAccount).WithMany(p => p.FundTransferTransferFromAccounts)
                .HasForeignKey(d => d.TransferFromAccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FundTransfer_TransferFromAccount");

            entity.HasOne(d => d.TransferToAccount).WithMany(p => p.FundTransferTransferToAccounts)
                .HasForeignKey(d => d.TransferToAccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FundTransfer_TransferToAccount");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<FundTransfer> entity);
    }
}
