// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Application.Core.Data;
using Application.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Application.Core.Data.Configurations
{
    public partial class GoodsReceiveNoteConfiguration : IEntityTypeConfiguration<GoodsReceiveNote>
    {
        public void Configure(EntityTypeBuilder<GoodsReceiveNote> entity)
        {
            entity.ToTable("GoodsReceiveNote");

            entity.HasIndex(e => e.Grnno, "UQ_GRNNo").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.AdditionalLandedCost).HasColumnType("decimal(22, 12)");
            entity.Property(e => e.ApprovedBy).HasMaxLength(100);
            entity.Property(e => e.ChallanNo).HasMaxLength(200);
            entity.Property(e => e.CheckedBy).HasMaxLength(100);
            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.Discount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.DriverContactNo).HasMaxLength(200);
            entity.Property(e => e.DriverName).HasMaxLength(200);
            entity.Property(e => e.ExchangeRate).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Grndate).HasColumnName("GRNDate");
            entity.Property(e => e.Grnno)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("GRNNo");
            entity.Property(e => e.LcNumber).HasMaxLength(200);
            entity.Property(e => e.Ponumber)
                .HasMaxLength(200)
                .HasColumnName("PONumber");
            entity.Property(e => e.ProformaInvoiceNo).HasMaxLength(200);
            entity.Property(e => e.PurchaseOrderTotal).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Subtotal).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Total).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TotalGrnAdjustmentAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TransportationCost).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TruckNo).HasMaxLength(100);
            entity.Property(e => e.UnpostedBy).HasMaxLength(100);
            entity.Property(e => e.UpdatedBy).HasMaxLength(100);

            entity.HasOne(d => d.Store).WithMany(p => p.GoodsReceiveNotes)
                .HasForeignKey(d => d.StoreId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GoodsReceiveNote_Store");

            entity.HasOne(d => d.Supplier).WithMany(p => p.GoodsReceiveNotes)
                .HasForeignKey(d => d.SupplierId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GoodsReceiveNote_Supplier");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<GoodsReceiveNote> entity);
    }
}
