// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Application.Core.Data;
using Application.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Application.Core.Data.Configurations
{
    public partial class GoodsReceiveNoteDetailConfiguration : IEntityTypeConfiguration<GoodsReceiveNoteDetail>
    {
        public void Configure(EntityTypeBuilder<GoodsReceiveNoteDetail> entity)
        {
            entity.ToTable("GoodsReceiveNoteDetail");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Amount).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.BatchNo).HasMaxLength(200);
            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.CurrencyAmount).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.CurrencyRate).HasColumnType("decimal(25, 18)");
            entity.Property(e => e.Grnquantity).HasColumnName("GRNQuantity");
            entity.Property(e => e.Poquantity).HasColumnName("POQuantity");
            entity.Property(e => e.Rate).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.RateAfterBagWeightDeduction).HasColumnType("decimal(25, 18)");
            entity.Property(e => e.UpdatedBy).HasMaxLength(100);

            entity.HasOne(d => d.GoodsReceiveNote).WithMany(p => p.GoodsReceiveNoteDetails)
                .HasForeignKey(d => d.GoodsReceiveNoteId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GoodsReceiveNoteDetail_GoodsReceiveNote");

            entity.HasOne(d => d.Product).WithMany(p => p.GoodsReceiveNoteDetails)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GoodsReceiveNoteDetail_Product");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<GoodsReceiveNoteDetail> entity);
    }
}
