// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Application.Core.Data;
using Application.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Application.Core.Data.Configurations
{
    public partial class JournalEntryConfiguration : IEntityTypeConfiguration<JournalEntry>
    {
        public void Configure(EntityTypeBuilder<JournalEntry> entity)
        {
            entity.ToTable("JournalEntry");

            entity.HasIndex(e => e.VoucherNo, "UQ_JournalEntry_VoucherNo").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.ApprovedBy).HasMaxLength(100);
            entity.Property(e => e.CheckedBy).HasMaxLength(100);
            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.UpdatedBy).HasMaxLength(100);
            entity.Property(e => e.VoucherNo)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.CostCenter).WithMany(p => p.JournalEntries)
                .HasForeignKey(d => d.CostCenterId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_JournalEntry_CostCenter");

            entity.Property(e => e.InactivatedBy).HasMaxLength(100);
            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<JournalEntry> entity);
    }
}
