// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Application.Core.Data;
using Application.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Application.Core.Data.Configurations
{
    public partial class LcAdjustmentConfiguration : IEntityTypeConfiguration<LcAdjustment>
    {
        public void Configure(EntityTypeBuilder<LcAdjustment> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK_LCAdjustment");

            entity.ToTable("LcAdjustment");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.ApprovedBy).HasMaxLength(100);
            entity.Property(e => e.CheckedBy).HasMaxLength(100);
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.InvoiceTotal).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.LcMarginTotal).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.PurchaseInvoiceNo)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.UpdatedBy).HasMaxLength(100);

            entity.HasOne(d => d.CostCenter).WithMany(p => p.LcAdjustments)
                .HasForeignKey(d => d.CostCenterId)
                .HasConstraintName("FK_LcAdjustment_CostCenter");

            entity.HasOne(d => d.PurchaseInvoice).WithMany(p => p.LcAdjustments)
                .HasForeignKey(d => d.PurchaseInvoiceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_LcAdjustment_PurchaseInvoice");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<LcAdjustment> entity);
    }
}
