// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Application.Core.Data;
using Application.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Application.Core.Data.Configurations
{
    public partial class LccostEntryDetailConfiguration : IEntityTypeConfiguration<LccostEntryDetail>
    {
        public void Configure(EntityTypeBuilder<LccostEntryDetail> entity)
        {
            entity.ToTable("LCCostEntryDetail");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.LccostEntryId).HasColumnName("LCCostEntryId");
            entity.Property(e => e.UpdatedBy).HasMaxLength(100);

            entity.HasOne(d => d.CreditAccount).WithMany(p => p.LccostEntryDetailCreditAccounts)
                .HasForeignKey(d => d.CreditAccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_LCCostEntryDetail_CreditAccount");

            entity.HasOne(d => d.DebitAccount).WithMany(p => p.LccostEntryDetailDebitAccounts)
                .HasForeignKey(d => d.DebitAccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_LCCostEntryDetail_DebitAccount");

            entity.HasOne(d => d.LccostEntry).WithMany(p => p.LccostEntryDetails)
                .HasForeignKey(d => d.LccostEntryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_LCCostEntryDetail_LCCostEntry");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<LccostEntryDetail> entity);
    }
}
