// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Application.Core.Data;
using Application.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Application.Core.Data.Configurations
{
    public partial class LccostEntryConfiguration : IEntityTypeConfiguration<LccostEntry>
    {
        public void Configure(EntityTypeBuilder<LccostEntry> entity)
        {
            entity.ToTable("LCCostEntry");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.ApprovedBy).HasMaxLength(100);
            entity.Property(e => e.CheckedBy).HasMaxLength(100);
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.LcNumber)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.Ponumber)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("PONumber");
            entity.Property(e => e.Total).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.UpdatedBy).HasMaxLength(100);

            entity.HasOne(d => d.CostCenter).WithMany(p => p.LccostEntries)
                .HasForeignKey(d => d.CostCenterId)
                .HasConstraintName("FK_LCCostEntry_CostCenter");

            entity.HasOne(d => d.PurchaseOrder).WithMany(p => p.LccostEntries)
                .HasForeignKey(d => d.PurchaseOrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_LCCostEntry_PurchaseOrder");

            entity.Property(e => e.InactivatedBy).HasMaxLength(100);
            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<LccostEntry> entity);
    }
}
