// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Application.Core.Data;
using Application.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Application.Core.Data.Configurations
{
    public partial class ManufacturingOrderConfiguration : IEntityTypeConfiguration<ManufacturingOrder>
    {
        public void Configure(EntityTypeBuilder<ManufacturingOrder> entity)
        {
            entity.ToTable("ManufacturingOrder");

            entity.HasIndex(e => e.ManufacturingOrderNo, "UQ_ManufacturingOrderNo").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.ApprovedBy).HasMaxLength(100);
            entity.Property(e => e.BomNo)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.CheckedBy).HasMaxLength(100);
            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.FormulationNo)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ManufacturingOrderNo)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.RmCost).HasColumnType("decimal(18, 6)");
            entity.Property(e => e.StandardDirectExpenseAmount).HasColumnType("decimal(18, 6)");
            entity.Property(e => e.StandardFactoryOverheadAmount).HasColumnType("decimal(18, 6)");
            entity.Property(e => e.TotalCost).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TotalRmused)
                .HasColumnType("decimal(18, 6)")
                .HasColumnName("TotalRMUsed");
            entity.Property(e => e.UnpostedBy).HasMaxLength(100);
            entity.Property(e => e.UpdatedBy).HasMaxLength(100);

            entity.HasOne(d => d.FinishedProduct).WithMany(p => p.ManufacturingOrders)
                .HasForeignKey(d => d.FinishedProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ManufacturingOrder_FinishedProduct");

            entity.HasOne(d => d.RawMaterialStore).WithMany(p => p.ManufacturingOrders)
                .HasForeignKey(d => d.RawMaterialStoreId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ManufacturingOrder_RawMaterialStore");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ManufacturingOrder> entity);
    }
}
