// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Application.Core.Data;
using Application.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Application.Core.Data.Configurations
{
    public partial class PaymentVoucherConfiguration : IEntityTypeConfiguration<PaymentVoucher>
    {
        public void Configure(EntityTypeBuilder<PaymentVoucher> entity)
        {
            entity.ToTable("PaymentVoucher");

            entity.HasIndex(e => e.VoucherNo, "UQ_PaymentVoucher_VoucherNo").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.ApprovedBy).HasMaxLength(100);
            entity.Property(e => e.CheckedBy).HasMaxLength(100);
            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.ReferenceNo)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.TotalAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TransactionNumber).HasMaxLength(100);
            entity.Property(e => e.UpdatedBy).HasMaxLength(100);
            entity.Property(e => e.VoucherNo)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.CashBankAccount).WithMany(p => p.PaymentVouchers)
                .HasForeignKey(d => d.CashBankAccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PaymentVoucher_CashBankAccount");

            entity.HasOne(d => d.CostCenter).WithMany(p => p.PaymentVouchers)
                .HasForeignKey(d => d.CostCenterId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PaymentVoucher_CostCenter");

            entity.HasOne(d => d.FundTransferTransactionType).WithMany(p => p.PaymentVouchers)
                .HasForeignKey(d => d.FundTransferTransactionTypeId)
                .HasConstraintName("FK_PaymentVoucher_FundTransferTransactionType");

            entity.HasOne(d => d.PaymentMode).WithMany(p => p.PaymentVouchers)
                .HasForeignKey(d => d.PaymentModeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PaymentVoucher_PaymentMode");

            entity.Property(e => e.InactivatedBy).HasMaxLength(100);
            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PaymentVoucher> entity);
    }
}
