// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Application.Core.Data;
using Application.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Application.Core.Data.Configurations
{
    public partial class PoPriceAdjustmentAfterGrnConfiguration : IEntityTypeConfiguration<PoPriceAdjustmentAfterGrn>
    {
        public void Configure(EntityTypeBuilder<PoPriceAdjustmentAfterGrn> entity)
        {
            entity.ToTable("PoPriceAdjustmentAfterGrn");

            entity.HasIndex(e => e.Code, "UQ_PoPriceAdjustmentAfterGrn_Code").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.ApprovedBy).HasMaxLength(100);
            entity.Property(e => e.CheckedBy).HasMaxLength(100);
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.Grnno)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("GRNNo");
            entity.Property(e => e.Ponumber)
                .HasMaxLength(20)
                .HasColumnName("PONumber");
            entity.Property(e => e.ReferenceNo).HasMaxLength(100);
            entity.Property(e => e.Remark).HasMaxLength(500);
            entity.Property(e => e.TotalAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.UpdatedBy).HasMaxLength(100);

            entity.HasOne(d => d.Store).WithMany(p => p.PoPriceAdjustmentAfterGrns)
                .HasForeignKey(d => d.StoreId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PoPriceAdjustmentAfterGrn_Store");

            entity.HasOne(d => d.Supplier).WithMany(p => p.PoPriceAdjustmentAfterGrns)
                .HasForeignKey(d => d.SupplierId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PoPriceAdjustmentAfterGrn_Supplier");

            entity.Property(e => e.InactivatedBy).HasMaxLength(100);
            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PoPriceAdjustmentAfterGrn> entity);
    }
}
