// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Application.Core.Data;
using Application.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Application.Core.Data.Configurations
{
    public partial class ProductAuditConfiguration : IEntityTypeConfiguration<ProductAudit>
    {
        public void Configure(EntityTypeBuilder<ProductAudit> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__ProductA__3214EC07F0C19D8C");

            entity.ToTable("ProductAudit");

            entity.Property(e => e.ActionType).HasMaxLength(20);
            entity.Property(e => e.BagWeight).HasDefaultValue(1);
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.LastPurchaseRate).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Mrp)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("MRP");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.PropertyName)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.PurchasePrice).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.SalePrice).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.UpdatedBy).HasMaxLength(100);
            entity.Property(e => e.VatPercentage).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.Category).WithMany(p => p.ProductAudits)
                .HasForeignKey(d => d.CategoryId)
                .HasConstraintName("FK_ProductAudit_Category");

            entity.HasOne(d => d.Country).WithMany(p => p.ProductAudits)
                .HasForeignKey(d => d.CountryId)
                .HasConstraintName("FK_ProductAudit_Country");

            entity.HasOne(d => d.Generic).WithMany(p => p.ProductAudits)
                .HasForeignKey(d => d.GenericId)
                .HasConstraintName("FK_ProductAudit_Generic");

            entity.HasOne(d => d.InventoryType).WithMany(p => p.ProductAudits)
                .HasForeignKey(d => d.InventoryTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductAudit_InventoryType");

            entity.HasOne(d => d.Manufacturer).WithMany(p => p.ProductAudits)
                .HasForeignKey(d => d.ManufacturerId)
                .HasConstraintName("FK_ProductAudit_Manufacturer");

            entity.HasOne(d => d.MeasurementUnit).WithMany(p => p.ProductAudits)
                .HasForeignKey(d => d.MeasurementUnitId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductAudit_MeasurementUnit");

            entity.HasOne(d => d.PackSize).WithMany(p => p.ProductAudits)
                .HasForeignKey(d => d.PackSizeId)
                .HasConstraintName("FK_ProductAudit_PackSize");

            entity.HasOne(d => d.ProductType).WithMany(p => p.ProductAudits)
                .HasForeignKey(d => d.ProductTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductAudit_ProductType");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ProductAudit> entity);
    }
}
