// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Application.Core.Data;
using Application.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Application.Core.Data.Configurations
{
    public partial class ProductionConfiguration : IEntityTypeConfiguration<Production>
    {
        public void Configure(EntityTypeBuilder<Production> entity)
        {
            entity.ToTable("Production");

            entity.HasIndex(e => e.ProductionNo, "UQ_ProductionNo").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.ApprovedBy).HasMaxLength(100);
            entity.Property(e => e.BatchNo)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.BomNo)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.CheckedBy).HasMaxLength(100);
            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.FgstoreId).HasColumnName("FGStoreId");
            entity.Property(e => e.FormulationNo)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ManufacturingOrderNo)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ProductionNo)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.RmCost).HasColumnType("decimal(18, 6)");
            entity.Property(e => e.TotalAdjustmentCost).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TotalAdjustmentQuantity).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TotalCost).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TotalRmused)
                .HasColumnType("decimal(18, 6)")
                .HasColumnName("TotalRMUsed");
            entity.Property(e => e.UnpostedBy).HasMaxLength(100);
            entity.Property(e => e.UpdatedBy).HasMaxLength(100);

            entity.HasOne(d => d.Fgstore).WithMany(p => p.Productions)
                .HasForeignKey(d => d.FgstoreId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Production_FinishedGoodsStore");

            entity.HasOne(d => d.FinishedProduct).WithMany(p => p.Productions)
                .HasForeignKey(d => d.FinishedProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Production_FinishedProduct");

            entity.HasOne(d => d.Machine).WithMany(p => p.Productions)
                .HasForeignKey(d => d.MachineId)
                .HasConstraintName("FK_Production_Machine");

            entity.HasOne(d => d.Shift).WithMany(p => p.Productions)
                .HasForeignKey(d => d.ShiftId)
                .HasConstraintName("FK_Production_Shift");

            entity.Property(e => e.InactivatedBy).HasMaxLength(100);
            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Production> entity);
    }
}
