// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Application.Core.Data;
using Application.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Application.Core.Data.Configurations
{
    public partial class ProductionDetailConfiguration : IEntityTypeConfiguration<ProductionDetail>
    {
        public void Configure(EntityTypeBuilder<ProductionDetail> entity)
        {
            entity.ToTable("ProductionDetail");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.ActualUsedQuantity).HasColumnType("decimal(18, 6)");
            entity.Property(e => e.AdjustmentQuantity).HasColumnType("decimal(18, 6)");
            entity.Property(e => e.AdjustmentValue).HasColumnType("decimal(18, 10)");
            entity.Property(e => e.Amount).HasColumnType("decimal(18, 10)");
            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.Quantity).HasColumnType("decimal(18, 6)");
            entity.Property(e => e.UpdatedBy).HasMaxLength(100);

            entity.HasOne(d => d.Production).WithMany(p => p.ProductionDetails)
                .HasForeignKey(d => d.ProductionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductionDetail_Production");

            entity.HasOne(d => d.RawMaterial).WithMany(p => p.ProductionDetails)
                .HasForeignKey(d => d.RawMaterialId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductionDetail_RawMaterial");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ProductionDetail> entity);
    }
}
