// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Application.Core.Data;
using Application.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Application.Core.Data.Configurations
{
    public partial class PurchaseRequisitionDetailConfiguration : IEntityTypeConfiguration<PurchaseRequisitionDetail>
    {
        public void Configure(EntityTypeBuilder<PurchaseRequisitionDetail> entity)
        {
            entity.ToTable("PurchaseRequisitionDetail");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Amount).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.CurrentStockQuantity).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.LastPurchaseRate).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.Rate).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.UpdatedBy).HasMaxLength(100);

            entity.HasOne(d => d.Product).WithMany(p => p.PurchaseRequisitionDetails)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PurchaseRequisitionDetail_Product");

            entity.HasOne(d => d.PurchaseRequisition).WithMany(p => p.PurchaseRequisitionDetails)
                .HasForeignKey(d => d.PurchaseRequisitionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PurchaseRequisitionDetail_PurchaseRequisition");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PurchaseRequisitionDetail> entity);
    }
}
