// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Application.Core.Data;
using Application.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Application.Core.Data.Configurations
{
    public partial class PurchaseInvoiceConfiguration : IEntityTypeConfiguration<PurchaseInvoice>
    {
        public void Configure(EntityTypeBuilder<PurchaseInvoice> entity)
        {
            entity.ToTable("PurchaseInvoice");

            entity.HasIndex(e => e.PurchaseInvoiceNo, "UQ_PurchaseInvoiceNo").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.AdditionalLandedCost).HasColumnType("decimal(22, 12)");
            entity.Property(e => e.AdjustmentValue).HasColumnType("decimal(22, 12)");
            entity.Property(e => e.AdvancePaymentAmount).HasColumnType("decimal(22, 2)");
            entity.Property(e => e.ApprovedBy).HasMaxLength(100);
            entity.Property(e => e.BillOfEntryNo).HasMaxLength(200);
            entity.Property(e => e.CheckedBy).HasMaxLength(100);
            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.Discount).HasColumnType("decimal(22, 2)");
            entity.Property(e => e.ExchangeRate).HasColumnType("decimal(22, 2)");
            entity.Property(e => e.Grnno).HasColumnName("GRNNo");
            entity.Property(e => e.LcNumber).HasMaxLength(200);
            entity.Property(e => e.NetPayable).HasColumnType("decimal(22, 2)");
            entity.Property(e => e.PaidAmount).HasColumnType("decimal(22, 2)");
            entity.Property(e => e.Ponumber)
                .HasMaxLength(200)
                .HasColumnName("PONumber");
            entity.Property(e => e.ProformaInvoiceNo).HasMaxLength(200);
            entity.Property(e => e.PurchaseInvoiceNo)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.PurchaseOrderTotal).HasColumnType("decimal(22, 2)");
            entity.Property(e => e.Subtotal).HasColumnType("decimal(22, 2)");
            entity.Property(e => e.SupplierInvoiceNo).HasMaxLength(200);
            entity.Property(e => e.Total).HasColumnType("decimal(22, 2)");
            entity.Property(e => e.TotalGrnAdjustmentAmount).HasColumnType("decimal(22, 2)");
            entity.Property(e => e.TotalVat).HasColumnType("decimal(22, 2)");
            entity.Property(e => e.TransportationCost).HasColumnType("decimal(22, 2)");
            entity.Property(e => e.UnpostedBy).HasMaxLength(100);
            entity.Property(e => e.UpdatedBy).HasMaxLength(100);

            entity.HasOne(d => d.Store).WithMany(p => p.PurchaseInvoices)
                .HasForeignKey(d => d.StoreId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PurchaseInvoice_Store");

            entity.HasOne(d => d.Supplier).WithMany(p => p.PurchaseInvoices)
                .HasForeignKey(d => d.SupplierId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PurchaseInvoice_Supplier");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PurchaseInvoice> entity);
    }
}
