// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Application.Core.Data;
using Application.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Application.Core.Data.Configurations
{
    public partial class PurchaseInvoiceDetailConfiguration : IEntityTypeConfiguration<PurchaseInvoiceDetail>
    {
        public void Configure(EntityTypeBuilder<PurchaseInvoiceDetail> entity)
        {
            entity.ToTable("PurchaseInvoiceDetail");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Amount).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.CurrencyAmount).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.CurrencyRate).HasColumnType("decimal(25, 18)");
            entity.Property(e => e.Grndate).HasColumnName("GRNDate");
            entity.Property(e => e.Grnno)
                .HasMaxLength(20)
                .HasColumnName("GRNNo");
            entity.Property(e => e.Grnquantity).HasColumnName("GRNQuantity");
            entity.Property(e => e.Rate).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.RateAfterBagWeightDeduction).HasColumnType("decimal(25, 18)");
            entity.Property(e => e.UpdatedBy).HasMaxLength(100);
            entity.Property(e => e.VatPercentage).HasColumnType("decimal(18, 4)");

            entity.HasOne(d => d.Product).WithMany(p => p.PurchaseInvoiceDetails)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PurchaseInvoiceDetail_Product");

            entity.HasOne(d => d.PurchaseInvoice).WithMany(p => p.PurchaseInvoiceDetails)
                .HasForeignKey(d => d.PurchaseInvoiceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PurchaseInvoiceDetail_PurchaseInvoice");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PurchaseInvoiceDetail> entity);
    }
}
