// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Application.Core.Data;
using Application.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Application.Core.Data.Configurations
{
    public partial class PurchaseOrderConfiguration : IEntityTypeConfiguration<PurchaseOrder>
    {
        public void Configure(EntityTypeBuilder<PurchaseOrder> entity)
        {
            entity.ToTable("PurchaseOrder");

            entity.HasIndex(e => e.Ponumber, "UQ_PONumber").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.AdditionalLandedCost).HasColumnType("decimal(22, 12)");
            entity.Property(e => e.ApprovedBy).HasMaxLength(100);
            entity.Property(e => e.CheckedBy).HasMaxLength(100);
            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.Discount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.ExchangeRate).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.ExpiryTime).HasMaxLength(250);
            entity.Property(e => e.LcNumber).HasMaxLength(200);
            entity.Property(e => e.PackagingType).HasMaxLength(500);
            entity.Property(e => e.Podate).HasColumnName("PODate");
            entity.Property(e => e.Ponumber)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("PONumber");
            entity.Property(e => e.ProductOrigin).HasMaxLength(500);
            entity.Property(e => e.ProformaInvoiceNo).HasMaxLength(200);
            entity.Property(e => e.QuotationNo).HasMaxLength(20);
            entity.Property(e => e.ReferenceNo).HasMaxLength(255);
            entity.Property(e => e.RequisitionNo).HasMaxLength(20);
            entity.Property(e => e.Subtotal).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Total).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.UpdatedBy).HasMaxLength(100);
            entity.Property(e => e.WeightVariance).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.DeliveryPlace).WithMany(p => p.PurchaseOrders)
                .HasForeignKey(d => d.DeliveryPlaceId)
                .HasConstraintName("FK_PurchaseOrder_DeliveryPlace");

            entity.HasOne(d => d.Store).WithMany(p => p.PurchaseOrders)
                .HasForeignKey(d => d.StoreId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PurchaseOrder_Store");

            entity.HasOne(d => d.Supplier).WithMany(p => p.PurchaseOrders)
                .HasForeignKey(d => d.SupplierId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PurchaseOrder_Supplier");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PurchaseOrder> entity);
    }
}
