// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Application.Core.Data;
using Application.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Application.Core.Data.Configurations
{
    public partial class PurchaseRequisitionPurchaseOrderMappingConfiguration : IEntityTypeConfiguration<PurchaseRequisitionPurchaseOrderMapping>
    {
        public void Configure(EntityTypeBuilder<PurchaseRequisitionPurchaseOrderMapping> entity)
        {
            entity.ToTable("PurchaseRequisitionPurchaseOrderMapping");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.PurchaseOrderRate).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.UpdatedBy).HasMaxLength(100);

            entity.HasOne(d => d.Product).WithMany(p => p.PurchaseRequisitionPurchaseOrderMappings)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PurchaseRequisitionPurchaseOrderMapping_Product");

            entity.HasOne(d => d.PurchaseOrder).WithMany(p => p.PurchaseRequisitionPurchaseOrderMappings)
                .HasForeignKey(d => d.PurchaseOrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PurchaseRequisitionPurchaseOrderMapping_PurchaseOrder");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PurchaseRequisitionPurchaseOrderMapping> entity);
    }
}
