// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Application.Core.Data;
using Application.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Application.Core.Data.Configurations
{
    public partial class ReceivePaymentAgainstSaleConfiguration : IEntityTypeConfiguration<ReceivePaymentAgainstSale>
    {
        public void Configure(EntityTypeBuilder<ReceivePaymentAgainstSale> entity)
        {
            entity.ToTable("ReceivePaymentAgainstSale");

            entity.HasIndex(e => e.Code, "UQ_ReceivePaymentAgainstSale_Code").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.ApprovedBy).HasMaxLength(100);
            entity.Property(e => e.CheckedBy).HasMaxLength(100);
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.UnpostedBy).HasMaxLength(100);
            entity.Property(e => e.UpdatedBy).HasMaxLength(100);

            entity.HasOne(d => d.CostCenter).WithMany(p => p.ReceivePaymentAgainstSales)
                .HasForeignKey(d => d.CostCenterId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ReceivePaymentAgainstSale_CostCenter");

            entity.HasOne(d => d.Customer).WithMany(p => p.ReceivePaymentAgainstSaleCustomers)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ReceivePaymentAgainstSale_Customer");

            entity.HasOne(d => d.ToAccount).WithMany(p => p.ReceivePaymentAgainstSaleToAccounts)
                .HasForeignKey(d => d.ToAccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ReceivePaymentAgainstSale_ToAccount");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ReceivePaymentAgainstSale> entity);
    }
}
