// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Application.Core.Data;
using Application.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Application.Core.Data.Configurations
{
    public partial class ReceivePaymentConfiguration : IEntityTypeConfiguration<ReceivePayment>
    {
        public void Configure(EntityTypeBuilder<ReceivePayment> entity)
        {
            entity.ToTable("ReceivePayment");

            entity.HasIndex(e => new { e.Deleted, e.TenantId }, "IX_ReceivePayment_TenantId_Deleted");

            entity.HasIndex(e => e.Code, "UQ_ReceivePayment_Code").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.ApprovedBy).HasMaxLength(100);
            entity.Property(e => e.CheckedBy).HasMaxLength(100);
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.CreditRecoveryPurpose).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.FeedSalesPurpose).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TotalAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TransactionNumber).HasMaxLength(100);
            entity.Property(e => e.UnpostedBy).HasMaxLength(100);
            entity.Property(e => e.UpdatedBy).HasMaxLength(100);

            entity.HasOne(d => d.CostCenter).WithMany(p => p.ReceivePayments)
                .HasForeignKey(d => d.CostCenterId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ReceivePayment_CostCenter");

            entity.HasOne(d => d.Customer).WithMany(p => p.ReceivePayments)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ReceivePayment_Customer");

            entity.HasOne(d => d.FundTransferTransactionType).WithMany(p => p.ReceivePayments)
                .HasForeignKey(d => d.FundTransferTransactionTypeId)
                .HasConstraintName("FK_ReceivePayment_FundTransferTransactionType");

            entity.HasOne(d => d.PaymentMode).WithMany(p => p.ReceivePayments)
                .HasForeignKey(d => d.PaymentModeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ReceivePayment_PaymentMode");

            entity.Property(e => e.InactivatedBy).HasMaxLength(100);
            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ReceivePayment> entity);
    }
}
