// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Application.Core.Data;
using Application.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Application.Core.Data.Configurations
{
    public partial class ReceiveVoucherDetailConfiguration : IEntityTypeConfiguration<ReceiveVoucherDetail>
    {
        public void Configure(EntityTypeBuilder<ReceiveVoucherDetail> entity)
        {
            entity.ToTable("ReceiveVoucherDetail");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.UpdatedBy).HasMaxLength(100);

            entity.HasOne(d => d.Account).WithMany(p => p.ReceiveVoucherDetails)
                .HasForeignKey(d => d.AccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ReceiveVoucherDetail_Account");

            entity.HasOne(d => d.ReceiveVoucher).WithMany(p => p.ReceiveVoucherDetails)
                .HasForeignKey(d => d.ReceiveVoucherId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ReceiveVoucherDetail_ReceiveVoucher");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ReceiveVoucherDetail> entity);
    }
}
