// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Application.Core.Data;
using Application.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Application.Core.Data.Configurations
{
    public partial class ReceivePaymentPictureMappingConfiguration : IEntityTypeConfiguration<ReceivePaymentPictureMapping>
    {
        public void Configure(EntityTypeBuilder<ReceivePaymentPictureMapping> entity)
        {
            entity.ToTable("ReceivePaymentPictureMapping");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.UpdatedBy).HasMaxLength(100);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ReceivePaymentPictureMapping> entity);
    }
}
