// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Application.Core.Data;
using Application.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Application.Core.Data.Configurations
{
    public partial class RfqSentConfiguration : IEntityTypeConfiguration<RfqSent>
    {
        public void Configure(EntityTypeBuilder<RfqSent> entity)
        {
            entity.ToTable("RfqSent");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.UpdatedBy).HasMaxLength(100);

            entity.HasOne(d => d.Requisition).WithMany(p => p.RfqSents)
                .HasForeignKey(d => d.RequisitionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RfqSent_PurchaseRequisition");

            entity.HasOne(d => d.Supplier).WithMany(p => p.RfqSents)
                .HasForeignKey(d => d.SupplierId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RfqSent_Supplier");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RfqSent> entity);
    }
}
