// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Application.Core.Data;
using Application.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Application.Core.Data.Configurations
{
    public partial class SaleQuotationDetailConfiguration : IEntityTypeConfiguration<SaleQuotationDetail>
    {
        public void Configure(EntityTypeBuilder<SaleQuotationDetail> entity)
        {
            entity.ToTable("SaleQuotationDetail");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Amount).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.DiscountAmount).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.DiscountPerUnit).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.Rate).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.UpdatedBy).HasMaxLength(100);

            entity.HasOne(d => d.Product).WithMany(p => p.SaleQuotationDetails)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SaleQuotationDetail_Product");

            entity.HasOne(d => d.SaleQuotation).WithMany(p => p.SaleQuotationDetails)
                .HasForeignKey(d => d.SaleQuotationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SaleQuotationDetail_SaleQuotation");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SaleQuotationDetail> entity);
    }
}
