// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Application.Core.Data;
using Application.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Application.Core.Data.Configurations
{
    public partial class SaleOrderConfiguration : IEntityTypeConfiguration<SaleOrder>
    {
        public void Configure(EntityTypeBuilder<SaleOrder> entity)
        {
            entity.ToTable("SaleOrder");

            entity.HasIndex(e => e.SaleOrderNo, "UQ_SaleOrderNo").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.ApprovedBy).HasMaxLength(100);
            entity.Property(e => e.CheckedBy).HasMaxLength(100);
            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.CreditLimit).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.DepoCharge).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Discount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.LimitAvailed).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.NetTotal).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.OfferDiscount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.OtherDiscount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.QuotationNo)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ReferenceNo)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.SaleOrderNo)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Subtotal).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Total).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TotalPercentageDiscountAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TransportationCost).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.UpdatedBy).HasMaxLength(100);

            entity.HasOne(d => d.Customer).WithMany(p => p.SaleOrders)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SaleOrder_Customer");

            entity.HasOne(d => d.CustomerTerritory).WithMany(p => p.SaleOrders)
                .HasForeignKey(d => d.CustomerTerritoryId)
                .HasConstraintName("FK_SaleOrder_CustomerTerritory");

            entity.HasOne(d => d.Store).WithMany(p => p.SaleOrders)
                .HasForeignKey(d => d.StoreId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SaleOrder_Store");

            entity.Property(e => e.InactivatedBy).HasMaxLength(100);
            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SaleOrder> entity);
    }
}
