// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Application.Core.Data;
using Application.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Application.Core.Data.Configurations
{
    public partial class SaleInvoiceConfiguration : IEntityTypeConfiguration<SaleInvoice>
    {
        public void Configure(EntityTypeBuilder<SaleInvoice> entity)
        {
            entity.ToTable("SaleInvoice");

            entity.HasIndex(e => e.InvoiceNo, "UQ_InvoiceNo").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.ApprovedBy).HasMaxLength(100);
            entity.Property(e => e.AvailableReceivable).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Balance).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.BankDetails).HasMaxLength(500);
            entity.Property(e => e.CheckedBy).HasMaxLength(100);
            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.DeliveryNoteNo)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.DepoCharge).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Discount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.InvoiceNo)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.NetTotal).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.OfferDiscount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.OtherDiscount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Paid).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.ReferenceNo).HasMaxLength(100);
            entity.Property(e => e.SaleOrderNo).HasMaxLength(100);
            entity.Property(e => e.Subtotal).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TermAndCondition).HasMaxLength(500);
            entity.Property(e => e.Total).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TotalPercentageDiscountAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TotalVat).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TransportationCost).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.UnpostedBy).HasMaxLength(100);
            entity.Property(e => e.UpdatedBy).HasMaxLength(100);

            entity.HasOne(d => d.Customer).WithMany(p => p.SaleInvoices)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SaleInvoice_Customer");

            entity.HasOne(d => d.CustomerTerritory).WithMany(p => p.SaleInvoices)
                .HasForeignKey(d => d.CustomerTerritoryId)
                .HasConstraintName("FK_SaleInvoice_CustomerTerritory");

            entity.HasOne(d => d.Store).WithMany(p => p.SaleInvoices)
                .HasForeignKey(d => d.StoreId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SaleInvoice_Store");

            entity.Property(e => e.InactivatedBy).HasMaxLength(100);
            entity.Property(e => e.StockIssuedBy).HasMaxLength(100);
            entity.Property(e => e.AdjustmentOtherDiscount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TotalAdjustmentAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TotalAdjustmentPercentageDiscountAmount).HasColumnType("decimal(18, 2)");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SaleInvoice> entity);
    }
}
