// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Application.Core.Data;
using Application.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Application.Core.Data.Configurations
{
    public partial class SaleReturnDetailConfiguration : IEntityTypeConfiguration<SaleReturnDetail>
    {
        public void Configure(EntityTypeBuilder<SaleReturnDetail> entity)
        {
            entity.ToTable("SaleReturnDetail");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Amount).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.DiscountPercentage).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.MonthlyDiscountPerUnit).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.OtherDiscountPerUnit).HasColumnType("decimal(20, 12)");
            entity.Property(e => e.PercentageDiscountAmount).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.Rate).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.TargetDiscountPerUnit).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.UpdatedBy).HasMaxLength(100);
            entity.Property(e => e.VatPercentage).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.YearlyDiscountPerUnit).HasColumnType("decimal(18, 4)");

            entity.HasOne(d => d.Product).WithMany(p => p.SaleReturnDetails)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SaleReturnDetail_Product");

            entity.HasOne(d => d.SaleReturn).WithMany(p => p.SaleReturnDetails)
                .HasForeignKey(d => d.SaleReturnId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SaleReturnDetail_SaleReturn");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SaleReturnDetail> entity);
    }
}
