// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Application.Core.Data;
using Application.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Application.Core.Data.Configurations
{
    public partial class SaleOrderDetailConfiguration : IEntityTypeConfiguration<SaleOrderDetail>
    {
        public void Configure(EntityTypeBuilder<SaleOrderDetail> entity)
        {
            entity.ToTable("SaleOrderDetail");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Amount).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.CashDiscountPerUnit).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.DepoChargePerUnit).HasColumnType("decimal(20, 12)");
            entity.Property(e => e.DiscountAmount).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.DiscountPerUnit).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.DiscountPercentage).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.InvoiceDiscountPerUnit).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.NetRate).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.OfferDiscountPerUnit).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.OtherDiscountPerUnit).HasColumnType("decimal(20, 12)");
            entity.Property(e => e.PercentageDiscountAmount).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.Rate).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.SpecialDiscountPerUnit).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.TransportationCostPerUnit).HasColumnType("decimal(20, 12)");
            entity.Property(e => e.UpdatedBy).HasMaxLength(100);
            entity.Property(e => e.VatPercentage).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.Product).WithMany(p => p.SaleOrderDetails)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SaleOrderDetail_Product");

            entity.HasOne(d => d.SaleOrder).WithMany(p => p.SaleOrderDetails)
                .HasForeignKey(d => d.SaleOrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SaleOrderDetail_SaleOrder");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SaleOrderDetail> entity);
    }
}
