// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Application.Core.Data;
using Application.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Application.Core.Data.Configurations
{
    public partial class StockConfiguration : IEntityTypeConfiguration<Stock>
    {
        public void Configure(EntityTypeBuilder<Stock> entity)
        {
            entity.ToTable("Stock");

            entity.HasIndex(e => e.AvailableQty, "idx_available_quantity_non_zero").HasFilter("([AvailableQty]<>(0))");

            entity.HasIndex(e => e.FinancialYearId, "idx_stock_financialyearid");

            entity.HasIndex(e => e.ProductId, "idx_stock_productid");

            entity.HasIndex(e => e.StockInDate, "idx_stock_stockindate");

            entity.HasIndex(e => e.StoreId, "idx_stock_storeid");

            entity.HasIndex(e => e.TenantId, "idx_stock_tenantid");

            entity.HasIndex(e => e.TransactonType, "idx_stock_transactiontype");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.AvailableQty).HasColumnType("decimal(18, 6)");
            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.InQty).HasColumnType("decimal(18, 6)");
            entity.Property(e => e.InRate).HasColumnType("decimal(18, 12)");
            entity.Property(e => e.InTransportCost).HasColumnType("decimal(18, 12)");
            entity.Property(e => e.OutQty).HasColumnType("decimal(18, 6)");
            entity.Property(e => e.OutRate).HasColumnType("decimal(18, 12)");
            entity.Property(e => e.Remark).HasMaxLength(255);
            entity.Property(e => e.UpdatedBy).HasMaxLength(100);

            entity.HasOne(d => d.Product).WithMany(p => p.Stocks)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Stock_Product");

            entity.HasOne(d => d.Store).WithMany(p => p.Stocks)
                .HasForeignKey(d => d.StoreId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Stock_Store");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Stock> entity);
    }
}
