// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Application.Core.Data;
using Application.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Application.Core.Data.Configurations
{
    public partial class StockAdjustmentDetailConfiguration : IEntityTypeConfiguration<StockAdjustmentDetail>
    {
        public void Configure(EntityTypeBuilder<StockAdjustmentDetail> entity)
        {
            entity.ToTable("StockAdjustmentDetail");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.AdjustmentQty).HasColumnType("decimal(18, 6)");
            entity.Property(e => e.AdjustmentValue).HasColumnType("decimal(18, 10)");
            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.UpdatedBy).HasMaxLength(100);

            entity.HasOne(d => d.Product).WithMany(p => p.StockAdjustmentDetails)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_StockAdjustmentDetail_Product");

            entity.HasOne(d => d.StockAdjustment).WithMany(p => p.StockAdjustmentDetails)
                .HasForeignKey(d => d.StockAdjustmentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_StockAdjustmentDetail_StockAdjustment");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<StockAdjustmentDetail> entity);
    }
}
