// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Application.Core.Data;
using Application.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Application.Core.Data.Configurations
{
    public partial class SupplierTransactionAgainstPoConfiguration : IEntityTypeConfiguration<SupplierTransactionAgainstPo>
    {
        public void Configure(EntityTypeBuilder<SupplierTransactionAgainstPo> entity)
        {
            entity.ToTable("SupplierTransactionAgainstPo");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.UpdatedBy).HasMaxLength(100);

            entity.HasOne(d => d.PurchaseOrder).WithMany(p => p.SupplierTransactionAgainstPos)
                .HasForeignKey(d => d.PurchaseOrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SupplierTransactionAgainstPo_PurchaseOrder");

            entity.HasOne(d => d.Supplier).WithMany(p => p.SupplierTransactionAgainstPos)
                .HasForeignKey(d => d.SupplierId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SupplierTransactionAgainstPo_Supplier");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SupplierTransactionAgainstPo> entity);
    }
}
