// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Application.Core.Data;
using Application.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Application.Core.Data.Configurations
{
    public partial class SupplierPaymentDetailConfiguration : IEntityTypeConfiguration<SupplierPaymentDetail>
    {
        public void Configure(EntityTypeBuilder<SupplierPaymentDetail> entity)
        {
            entity.ToTable("SupplierPaymentDetail");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.AccountDescription).IsRequired();
            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.PurchaseInvoiceNo).HasMaxLength(20);
            entity.Property(e => e.UpdatedBy).HasMaxLength(100);

            entity.HasOne(d => d.Account).WithMany(p => p.SupplierPaymentDetails)
                .HasForeignKey(d => d.AccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SupplierPaymentDetail_Account");

            entity.HasOne(d => d.SupplierPayment).WithMany(p => p.SupplierPaymentDetails)
                .HasForeignKey(d => d.SupplierPaymentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SupplierPaymentDetail_SupplierPayment");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SupplierPaymentDetail> entity);
    }
}
