// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Application.Core.Data;
using Application.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Application.Core.Data.Configurations
{
    public partial class SupplierPaymentAgainstPurchaseConfiguration : IEntityTypeConfiguration<SupplierPaymentAgainstPurchase>
    {
        public void Configure(EntityTypeBuilder<SupplierPaymentAgainstPurchase> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK_SupplierPayment");

            entity.ToTable("SupplierPaymentAgainstPurchase");

            entity.HasIndex(e => e.Code, "UQ_SupplierPaymentAgainstPurchase_Code").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.ApprovedBy).HasMaxLength(100);
            entity.Property(e => e.CheckedBy).HasMaxLength(100);
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.UnpostedBy).HasMaxLength(100);
            entity.Property(e => e.UpdatedBy).HasMaxLength(100);

            entity.HasOne(d => d.CostCenter).WithMany(p => p.SupplierPaymentAgainstPurchases)
                .HasForeignKey(d => d.CostCenterId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SupplierPayment_CostCenter");

            entity.HasOne(d => d.FromAccount).WithMany(p => p.SupplierPaymentAgainstPurchases)
                .HasForeignKey(d => d.FromAccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SupplierPayment_FromAccount");

            entity.HasOne(d => d.PurchaseInvoice).WithMany(p => p.SupplierPaymentAgainstPurchases)
                .HasForeignKey(d => d.PurchaseInvoiceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SupplierPayment_PurchaseInvoice");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SupplierPaymentAgainstPurchase> entity);
    }
}
