// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Application.Core.Data;
using Application.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Application.Core.Data.Configurations
{
    public partial class SupplierPaymentConfiguration : IEntityTypeConfiguration<SupplierPayment>
    {
        public void Configure(EntityTypeBuilder<SupplierPayment> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK_SupplierPayment_1");

            entity.ToTable("SupplierPayment");

            entity.HasIndex(e => e.Code, "UQ_SupplierPayment_Code").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.ApprovedBy).HasMaxLength(100);
            entity.Property(e => e.CheckedBy).HasMaxLength(100);
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.Ponumber)
                .HasMaxLength(20)
                .HasColumnName("PONumber");
            entity.Property(e => e.TotalAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TransactionNumber).HasMaxLength(100);
            entity.Property(e => e.UnpostedBy).HasMaxLength(100);
            entity.Property(e => e.UpdatedBy).HasMaxLength(100);
            entity.Property(e => e.UsedAmountInPurchaseInvoice).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.CostCenter).WithMany(p => p.SupplierPayments)
                .HasForeignKey(d => d.CostCenterId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SupplierPayment1_CostCenter");

            entity.HasOne(d => d.FundTransferTransactionType).WithMany(p => p.SupplierPayments)
                .HasForeignKey(d => d.FundTransferTransactionTypeId)
                .HasConstraintName("FK_SupplierPayment_FundTransferTransactionType");

            entity.HasOne(d => d.PaymentMode).WithMany(p => p.SupplierPayments)
                .HasForeignKey(d => d.PaymentModeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SupplierPayment_PaymentMode");

            entity.HasOne(d => d.Supplier).WithMany(p => p.SupplierPayments)
                .HasForeignKey(d => d.SupplierId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SupplierPayment_Supplier");

            entity.Property(e => e.InactivatedBy).HasMaxLength(100);
            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SupplierPayment> entity);
    }
}
