// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Application.Core.Data;
using Application.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Application.Core.Data.Configurations
{
    public partial class TenantConfiguration : IEntityTypeConfiguration<Tenant>
    {
        public void Configure(EntityTypeBuilder<Tenant> entity)
        {
            entity.ToTable("Tenant");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Binno)
                .HasMaxLength(255)
                .HasColumnName("BINNo");
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.ContactNo).HasMaxLength(50);
            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.Email).HasMaxLength(255);
            entity.Property(e => e.Logo).HasMaxLength(50);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.UpdatedBy).HasMaxLength(100);

            // ---- Platform layer (Phase 1) ----
            entity.Property(e => e.Subdomain).HasMaxLength(63);
            entity.Property(e => e.CustomDomain).HasMaxLength(253);
            entity.Property(e => e.BusinessTemplateKey).HasMaxLength(50);
            entity.Property(e => e.Status).HasMaxLength(20);
            entity.Property(e => e.Currency).HasMaxLength(3);
            entity.Property(e => e.DbConnectionKey).HasMaxLength(100);
            entity.HasIndex(e => e.Subdomain)
                .IsUnique()
                .HasFilter("[Subdomain] IS NOT NULL");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Tenant> entity);
    }
}
