// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Application.Core.Data;
using Application.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Application.Core.Data.Configurations
{
    public partial class VendorQuotationDetailConfiguration : IEntityTypeConfiguration<VendorQuotationDetail>
    {
        public void Configure(EntityTypeBuilder<VendorQuotationDetail> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK_VendorQuotaionDetail");

            entity.ToTable("VendorQuotationDetail");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Amount).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.Rate).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.UpdatedBy).HasMaxLength(100);

            entity.HasOne(d => d.Product).WithMany(p => p.VendorQuotationDetails)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VendorQuotaionDetail_Product");

            entity.HasOne(d => d.VendorQuotation).WithMany(p => p.VendorQuotationDetails)
                .HasForeignKey(d => d.VendorQuotationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VendorQuotaionDetail_VendorQuotation");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VendorQuotationDetail> entity);
    }
}
