// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Application.Core.Data;
using Application.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Application.Core.Data.Configurations
{
    public partial class VoucherEntryDetailConfiguration : IEntityTypeConfiguration<VoucherEntryDetail>
    {
        public void Configure(EntityTypeBuilder<VoucherEntryDetail> entity)
        {
            entity.ToTable("VoucherEntryDetail");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.UpdatedBy).HasMaxLength(100);

            entity.HasOne(d => d.Account).WithMany(p => p.VoucherEntryDetails)
                .HasForeignKey(d => d.AccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VoucherEntryDetail_Account");

            entity.HasOne(d => d.VoucherEntry).WithMany(p => p.VoucherEntryDetails)
                .HasForeignKey(d => d.VoucherEntryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VoucherEntryDetail_VoucherEntry");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VoucherEntryDetail> entity);
    }
}
