// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Application.Core.Data.Configurations;
using Application.Core.Entities;
using Application.Core.Extensions;
using Application.Core.StoredProcedureResult;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
#nullable disable

namespace Application.Core.Data;

public partial class DataContext : DbContext
{
    public DataContext(DbContextOptions<DataContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Account> Accounts { get; set; }

    public virtual DbSet<AccountType> AccountTypes { get; set; }

    public virtual DbSet<Area> Areas { get; set; }

    public virtual DbSet<BankAccount> BankAccounts { get; set; }

    public virtual DbSet<BillOfMaterial> BillOfMaterials { get; set; }

    public virtual DbSet<BillOfMaterialDetail> BillOfMaterialDetails { get; set; }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<Company> Companies { get; set; }

    public virtual DbSet<CostCenter> CostCenters { get; set; }

    public virtual DbSet<Country> Countries { get; set; }

    public virtual DbSet<Currency> Currencies { get; set; }

    public virtual DbSet<CustomerWiseProductDiscount> CustomerWiseProductDiscounts { get; set; }

    public virtual DbSet<CustomerWiseProductDiscountDetail> CustomerWiseProductDiscountDetails { get; set; }

    public virtual DbSet<CustomerWiseProductDiscountUsageHistory> CustomerWiseProductDiscountUsageHistories { get; set; }

    public virtual DbSet<DeliveryNote> DeliveryNotes { get; set; }

    public virtual DbSet<DeliveryNoteDetail> DeliveryNoteDetails { get; set; }

    public virtual DbSet<DeliveryPlace> DeliveryPlaces { get; set; }

    public virtual DbSet<Department> Departments { get; set; }

    public virtual DbSet<Designation> Designations { get; set; }

    public virtual DbSet<DiscountProductWise> DiscountProductWises { get; set; }

    public virtual DbSet<DiscountProductWiseDetail> DiscountProductWiseDetails { get; set; }

    public virtual DbSet<DiscountProductWiseUsageHistory> DiscountProductWiseUsageHistories { get; set; }

    public virtual DbSet<EmailAccount> EmailAccounts { get; set; }

    public virtual DbSet<Employee> Employees { get; set; }

    public virtual DbSet<EventLog> EventLogs { get; set; }

    public virtual DbSet<FinancialYear> FinancialYears { get; set; }

    public virtual DbSet<FundTransfer> FundTransfers { get; set; }

    public virtual DbSet<FundTransferTransactionType> FundTransferTransactionTypes { get; set; }

    public virtual DbSet<Generic> Generics { get; set; }

    public virtual DbSet<GoodsReceiveNote> GoodsReceiveNotes { get; set; }

    public virtual DbSet<GoodsReceiveNoteDetail> GoodsReceiveNoteDetails { get; set; }

    public virtual DbSet<InventoryType> InventoryTypes { get; set; }

    public virtual DbSet<JobLocation> JobLocations { get; set; }

    public virtual DbSet<JournalEntry> JournalEntries { get; set; }

    public virtual DbSet<JournalEntryDetail> JournalEntryDetails { get; set; }

    public virtual DbSet<LcAdjustment> LcAdjustments { get; set; }

    public virtual DbSet<LcAdjustmentDetail> LcAdjustmentDetails { get; set; }

    public virtual DbSet<LccostEntry> LccostEntries { get; set; }

    public virtual DbSet<LccostEntryDetail> LccostEntryDetails { get; set; }

    public virtual DbSet<Log> Logs { get; set; }

    public virtual DbSet<Machine> Machines { get; set; }

    public virtual DbSet<Manufacturer> Manufacturers { get; set; }

    public virtual DbSet<ManufacturingOrder> ManufacturingOrders { get; set; }

    public virtual DbSet<ManufacturingOrderDetail> ManufacturingOrderDetails { get; set; }

    public virtual DbSet<MeasurementUnit> MeasurementUnits { get; set; }

    public virtual DbSet<Notification> Notifications { get; set; }

    public virtual DbSet<PackSize> PackSizes { get; set; }

    public virtual DbSet<PaymentMethod> PaymentMethods { get; set; }

    public virtual DbSet<PaymentMode> PaymentModes { get; set; }

    public virtual DbSet<PaymentVoucher> PaymentVouchers { get; set; }

    public virtual DbSet<PaymentVoucherDetail> PaymentVoucherDetails { get; set; }

    public virtual DbSet<Picture> Pictures { get; set; }

    public virtual DbSet<PoPriceAdjustmentAfterGrn> PoPriceAdjustmentAfterGrns { get; set; }

    public virtual DbSet<PoPriceAdjustmentAfterGrnDetail> PoPriceAdjustmentAfterGrnDetails { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<ProductAudit> ProductAudits { get; set; }

    public virtual DbSet<ProductCostSetup> ProductCostSetups { get; set; }

    public virtual DbSet<ProductType> ProductTypes { get; set; }

    public virtual DbSet<Production> Productions { get; set; }

    public virtual DbSet<ProductionDetail> ProductionDetails { get; set; }

    public virtual DbSet<PurchaseInvoice> PurchaseInvoices { get; set; }

    public virtual DbSet<PurchaseInvoiceDetail> PurchaseInvoiceDetails { get; set; }

    public virtual DbSet<PurchaseInvoiceSupplierPaymentMapping> PurchaseInvoiceSupplierPaymentMappings { get; set; }

    public virtual DbSet<PurchaseOrder> PurchaseOrders { get; set; }

    public virtual DbSet<PurchaseOrderDetail> PurchaseOrderDetails { get; set; }

    public virtual DbSet<PurchaseRequisition> PurchaseRequisitions { get; set; }

    public virtual DbSet<PurchaseRequisitionDetail> PurchaseRequisitionDetails { get; set; }

    public virtual DbSet<PurchaseRequisitionPurchaseOrderMapping> PurchaseRequisitionPurchaseOrderMappings { get; set; }

    public virtual DbSet<PurchaseReturn> PurchaseReturns { get; set; }

    public virtual DbSet<PurchaseReturnDetail> PurchaseReturnDetails { get; set; }

    public virtual DbSet<ReceivePayment> ReceivePayments { get; set; }

    public virtual DbSet<ReceivePaymentAgainstSale> ReceivePaymentAgainstSales { get; set; }

    public virtual DbSet<ReceivePaymentAgainstSaleSaleInvoiceMapping> ReceivePaymentAgainstSaleSaleInvoiceMappings { get; set; }

    public virtual DbSet<ReceivePaymentDetail> ReceivePaymentDetails { get; set; }

    public virtual DbSet<ReceivePaymentPictureMapping> ReceivePaymentPictureMappings { get; set; }

    public virtual DbSet<ReceiveVoucher> ReceiveVouchers { get; set; }

    public virtual DbSet<ReceiveVoucherDetail> ReceiveVoucherDetails { get; set; }

    public virtual DbSet<RefreshToken> RefreshTokens { get; set; }

    public virtual DbSet<Region> Regions { get; set; }

    public virtual DbSet<RfqSent> RfqSents { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<RoleClaim> RoleClaims { get; set; }

    public virtual DbSet<SaleInvoice> SaleInvoices { get; set; }

    public virtual DbSet<SaleInvoiceDetail> SaleInvoiceDetails { get; set; }

    public virtual DbSet<SaleOrder> SaleOrders { get; set; }

    public virtual DbSet<SaleOrderDetail> SaleOrderDetails { get; set; }

    public virtual DbSet<SaleQuotation> SaleQuotations { get; set; }

    public virtual DbSet<SaleQuotationDetail> SaleQuotationDetails { get; set; }

    public virtual DbSet<SaleReturn> SaleReturns { get; set; }

    public virtual DbSet<SaleReturnDetail> SaleReturnDetails { get; set; }

    public virtual DbSet<Setting> Settings { get; set; }

    public virtual DbSet<Shift> Shifts { get; set; }

    public virtual DbSet<Stock> Stocks { get; set; }

    public virtual DbSet<StockAdjustment> StockAdjustments { get; set; }

    public virtual DbSet<StockAdjustmentDetail> StockAdjustmentDetails { get; set; }

    public virtual DbSet<StockTransfer> StockTransfers { get; set; }

    public virtual DbSet<StockTransferDetail> StockTransferDetails { get; set; }

    public virtual DbSet<Store> Stores { get; set; }

    public virtual DbSet<SupplierPayment> SupplierPayments { get; set; }

    public virtual DbSet<SupplierPaymentAgainstPurchase> SupplierPaymentAgainstPurchases { get; set; }

    public virtual DbSet<SupplierPaymentDetail> SupplierPaymentDetails { get; set; }

    public virtual DbSet<SupplierProductMapping> SupplierProductMappings { get; set; }

    public virtual DbSet<SupplierTransactionAgainstPo> SupplierTransactionAgainstPos { get; set; }

    public virtual DbSet<Tenant> Tenants { get; set; }

    public virtual DbSet<Territory> Territories { get; set; }

    public virtual DbSet<Transaction> Transactions { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<VendorQuotation> VendorQuotations { get; set; }

    public virtual DbSet<VendorQuotationDetail> VendorQuotationDetails { get; set; }

    public virtual DbSet<VoucherEntry> VoucherEntries { get; set; }

    public virtual DbSet<VoucherEntryDetail> VoucherEntryDetails { get; set; }

    public virtual DbSet<Zone> Zones { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new Configurations.AccountConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.AccountTypeConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.AreaConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.BankAccountConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.BillOfMaterialConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.BillOfMaterialDetailConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.CategoryConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.CompanyConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.CostCenterConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.CountryConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.CurrencyConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.CustomerWiseProductDiscountConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.CustomerWiseProductDiscountDetailConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.CustomerWiseProductDiscountUsageHistoryConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.DeliveryNoteConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.DeliveryNoteDetailConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.DeliveryPlaceConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.DepartmentConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.DesignationConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.DiscountProductWiseConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.DiscountProductWiseDetailConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.DiscountProductWiseUsageHistoryConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.EmailAccountConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.EmployeeConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.EventLogConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.FinancialYearConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.FundTransferConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.FundTransferTransactionTypeConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.GenericConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.GoodsReceiveNoteConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.GoodsReceiveNoteDetailConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.InventoryTypeConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.JobLocationConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.JournalEntryConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.JournalEntryDetailConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.LcAdjustmentConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.LcAdjustmentDetailConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.LccostEntryConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.LccostEntryDetailConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.LogConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.MachineConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ManufacturerConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ManufacturingOrderConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ManufacturingOrderDetailConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.MeasurementUnitConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.NotificationConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.PackSizeConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.PaymentMethodConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.PaymentModeConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.PaymentVoucherConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.PaymentVoucherDetailConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.PictureConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.PoPriceAdjustmentAfterGrnConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.PoPriceAdjustmentAfterGrnDetailConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ProductConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ProductAuditConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ProductCostSetupConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ProductTypeConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ProductionConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ProductionDetailConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.PurchaseInvoiceConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.PurchaseInvoiceDetailConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.PurchaseInvoiceSupplierPaymentMappingConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.PurchaseOrderConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.PurchaseOrderDetailConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.PurchaseRequisitionConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.PurchaseRequisitionDetailConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.PurchaseRequisitionPurchaseOrderMappingConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.PurchaseReturnConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.PurchaseReturnDetailConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ReceivePaymentConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ReceivePaymentAgainstSaleConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ReceivePaymentAgainstSaleSaleInvoiceMappingConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ReceivePaymentDetailConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ReceivePaymentPictureMappingConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ReceiveVoucherConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ReceiveVoucherDetailConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.RefreshTokenConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.RegionConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.RfqSentConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.RoleConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.RoleClaimConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.SaleInvoiceConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.SaleInvoiceDetailConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.SaleOrderConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.SaleOrderDetailConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.SaleQuotationConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.SaleQuotationDetailConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.SaleReturnConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.SaleReturnDetailConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.SettingConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ShiftConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.StockConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.StockAdjustmentConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.StockAdjustmentDetailConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.StockTransferConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.StockTransferDetailConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.StoreConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.SupplierPaymentConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.SupplierPaymentAgainstPurchaseConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.SupplierPaymentDetailConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.SupplierProductMappingConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.SupplierTransactionAgainstPoConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.TenantConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.TerritoryConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.TransactionConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.UserConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.VendorQuotationConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.VendorQuotationDetailConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.VoucherEntryConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.VoucherEntryDetailConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ZoneConfiguration());
        modelBuilder.ApplyGlobalFilter<bool>("Deleted", false);
        modelBuilder.Entity<SPSupplierLedgerResult>().HasNoKey();
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
