// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Application.Core.Entities;

public partial class Account
{
    public Guid Id { get; set; }

    public string Code { get; set; }

    public Guid AccountTypeId { get; set; }

    public int Level { get; set; }

    public string Name { get; set; }

    public Guid? ParentId { get; set; }

    public bool IsControlAccount { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime UpdatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public bool Deleted { get; set; }

    public string OwnersName { get; set; }

    public string ContactNo { get; set; }

    public string Email { get; set; }

    public string Address { get; set; }

    public string TradeLicense { get; set; }

    public string NationalId { get; set; }

    public string ContactPersonName { get; set; }

    public string ContactPersonContactNo { get; set; }

    public string ContactPersonEmail { get; set; }

    public string ContactPersonDesignation { get; set; }

    public Guid? CustomerRegionId { get; set; }

    public Guid? CustomerZoneId { get; set; }

    public Guid? CustomerAreaId { get; set; }

    public Guid? CustomerTerritoryId { get; set; }

    public Guid? CustomerMarketingOfficerId { get; set; }

    public decimal CustomerCreditLimit { get; set; }

    public bool CustomerAgreement { get; set; }

    public string CustomerCreditDays { get; set; }

    public string CustomerTargetQuantity { get; set; }

    public Guid TenantId { get; set; }

    public bool ForAppUser { get; set; }

    public virtual AccountType AccountType { get; set; }

    public virtual ICollection<BankAccount> BankAccounts { get; set; } = new List<BankAccount>();

    public virtual Employee CustomerMarketingOfficer { get; set; }

    public virtual ICollection<CustomerWiseProductDiscount> CustomerWiseProductDiscounts { get; set; } = new List<CustomerWiseProductDiscount>();

    public virtual ICollection<DeliveryNote> DeliveryNotes { get; set; } = new List<DeliveryNote>();

    public virtual ICollection<FundTransfer> FundTransferTransferFromAccounts { get; set; } = new List<FundTransfer>();

    public virtual ICollection<FundTransfer> FundTransferTransferToAccounts { get; set; } = new List<FundTransfer>();

    public virtual ICollection<GoodsReceiveNote> GoodsReceiveNotes { get; set; } = new List<GoodsReceiveNote>();

    public virtual ICollection<Account> InverseParent { get; set; } = new List<Account>();

    public virtual ICollection<JournalEntryDetail> JournalEntryDetails { get; set; } = new List<JournalEntryDetail>();

    public virtual ICollection<LcAdjustmentDetail> LcAdjustmentDetails { get; set; } = new List<LcAdjustmentDetail>();

    public virtual ICollection<LccostEntryDetail> LccostEntryDetailCreditAccounts { get; set; } = new List<LccostEntryDetail>();

    public virtual ICollection<LccostEntryDetail> LccostEntryDetailDebitAccounts { get; set; } = new List<LccostEntryDetail>();

    public virtual Account Parent { get; set; }

    public virtual ICollection<PaymentVoucherDetail> PaymentVoucherDetails { get; set; } = new List<PaymentVoucherDetail>();

    public virtual ICollection<PaymentVoucher> PaymentVouchers { get; set; } = new List<PaymentVoucher>();

    public virtual ICollection<PoPriceAdjustmentAfterGrn> PoPriceAdjustmentAfterGrns { get; set; } = new List<PoPriceAdjustmentAfterGrn>();

    public virtual ICollection<PurchaseInvoice> PurchaseInvoices { get; set; } = new List<PurchaseInvoice>();

    public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; } = new List<PurchaseOrder>();

    public virtual ICollection<PurchaseReturn> PurchaseReturns { get; set; } = new List<PurchaseReturn>();

    public virtual ICollection<ReceivePaymentAgainstSale> ReceivePaymentAgainstSaleCustomers { get; set; } = new List<ReceivePaymentAgainstSale>();

    public virtual ICollection<ReceivePaymentAgainstSale> ReceivePaymentAgainstSaleToAccounts { get; set; } = new List<ReceivePaymentAgainstSale>();

    public virtual ICollection<ReceivePaymentDetail> ReceivePaymentDetails { get; set; } = new List<ReceivePaymentDetail>();

    public virtual ICollection<ReceivePayment> ReceivePayments { get; set; } = new List<ReceivePayment>();

    public virtual ICollection<ReceiveVoucherDetail> ReceiveVoucherDetails { get; set; } = new List<ReceiveVoucherDetail>();

    public virtual ICollection<ReceiveVoucher> ReceiveVouchers { get; set; } = new List<ReceiveVoucher>();

    public virtual ICollection<RfqSent> RfqSents { get; set; } = new List<RfqSent>();

    public virtual ICollection<SaleInvoice> SaleInvoices { get; set; } = new List<SaleInvoice>();

    public virtual ICollection<SaleOrder> SaleOrders { get; set; } = new List<SaleOrder>();

    public virtual ICollection<SaleQuotation> SaleQuotations { get; set; } = new List<SaleQuotation>();

    public virtual ICollection<SaleReturn> SaleReturns { get; set; } = new List<SaleReturn>();

    public virtual ICollection<SupplierPaymentAgainstPurchase> SupplierPaymentAgainstPurchases { get; set; } = new List<SupplierPaymentAgainstPurchase>();

    public virtual ICollection<SupplierPaymentDetail> SupplierPaymentDetails { get; set; } = new List<SupplierPaymentDetail>();

    public virtual ICollection<SupplierPayment> SupplierPayments { get; set; } = new List<SupplierPayment>();

    public virtual ICollection<SupplierTransactionAgainstPo> SupplierTransactionAgainstPos { get; set; } = new List<SupplierTransactionAgainstPo>();

    public virtual ICollection<VendorQuotation> VendorQuotations { get; set; } = new List<VendorQuotation>();

    public virtual ICollection<VoucherEntry> VoucherEntries { get; set; } = new List<VoucherEntry>();

    public virtual ICollection<VoucherEntryDetail> VoucherEntryDetails { get; set; } = new List<VoucherEntryDetail>();
}