// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Application.Core.Entities;

public partial class BankAccount
{
    public Guid Id { get; set; }

    public Guid AccountId { get; set; }

    public string Name { get; set; }

    public string AccNo { get; set; }

    public string RoutingNo { get; set; }

    public string BankName { get; set; }

    public string BranchName { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime UpdatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public bool Deleted { get; set; }

    public Guid TenantId { get; set; }

    public virtual Account Account { get; set; }
}