// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Application.Core.Entities;

public partial class BillOfMaterial
{
    public Guid Id { get; set; }

    public string BomNo { get; set; }

    public string CopiedFromBomNo { get; set; }

    public Guid FinishedProductId { get; set; }

    public string FormulationNo { get; set; }

    public int DosageQuantity { get; set; }

    public int Status { get; set; }

    public decimal TotalQuantity { get; set; }

    public string CheckedBy { get; set; }

    public string ApprovedBy { get; set; }

    public string Remark { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime UpdatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public bool Deleted { get; set; }

    public Guid FinancialYearId { get; set; }

    public Guid TenantId { get; set; }

    public bool IsInactive { get; set; }

    public string InactivatedBy { get; set; }

    public virtual ICollection<BillOfMaterialDetail> BillOfMaterialDetails { get; set; } = new List<BillOfMaterialDetail>();

    public virtual Product FinishedProduct { get; set; }
}