// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Application.Core.Entities;

public partial class CustomerWiseProductDiscount
{
    public Guid Id { get; set; }

    public Guid CustomerId { get; set; }

    public DateTime ApplicableDate { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime UpdatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public bool Deleted { get; set; }

    public Guid TenantId { get; set; }

    public int Status { get; set; }

    public string CheckedBy { get; set; }

    public string ApprovedBy { get; set; }

    public string UnpostedBy { get; set; }

    public virtual Account Customer { get; set; }

    public virtual ICollection<CustomerWiseProductDiscountDetail> CustomerWiseProductDiscountDetails { get; set; } = new List<CustomerWiseProductDiscountDetail>();

    public virtual ICollection<CustomerWiseProductDiscountUsageHistory> CustomerWiseProductDiscountUsageHistories { get; set; } = new List<CustomerWiseProductDiscountUsageHistory>();
}