// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Application.Core.Entities;

public partial class DiscountProductWiseUsageHistory
{
    public Guid Id { get; set; }

    public Guid DiscountProductWiseId { get; set; }

    public Guid SaleOrderId { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime UpdatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public bool Deleted { get; set; }

    public Guid TenantId { get; set; }

    public virtual DiscountProductWise DiscountProductWise { get; set; }

    public virtual SaleOrder SaleOrder { get; set; }
}