// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Application.Core.Entities;

public partial class EmailAccount
{
    public Guid Id { get; set; }

    public string DisplayName { get; set; }

    public string Email { get; set; }

    public string Host { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public int Port { get; set; }

    public bool EnableSsl { get; set; }

    public bool IsDefaultEmailAccount { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime UpdatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public bool Deleted { get; set; }

    public Guid TenantId { get; set; }
}