// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Application.Core.Entities;

public partial class Employee
{
    public Guid Id { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string FullName { get; set; }

    public string EmployeeIdNo { get; set; }

    public string ContactNo { get; set; }

    public string Email { get; set; }

    public string Address { get; set; }

    public DateTime DateOfBirth { get; set; }

    public DateTime JoiningDate { get; set; }

    public int Gender { get; set; }

    public int BloodGroup { get; set; }

    public int MaritalStatus { get; set; }

    public Guid DepartmentId { get; set; }

    public Guid DesignationId { get; set; }

    public Guid JobLocationId { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime UpdatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public bool Deleted { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<Account> Accounts { get; set; } = new List<Account>();

    public virtual Department Department { get; set; }

    public virtual Designation Designation { get; set; }

    public virtual JobLocation JobLocation { get; set; }

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}