// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Application.Core.Entities;

public partial class EventLog
{
    public Guid Id { get; set; }

    public string TableName { get; set; }

    public string OldValues { get; set; }

    public string NewValues { get; set; }

    public DateTime CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public Guid? EntityId { get; set; }

    public string EventDescription { get; set; }

    public Guid TenantId { get; set; }
}