// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Application.Core.Entities;

public partial class FundTransferTransactionType
{
    public Guid Id { get; set; }

    public string Name { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime UpdatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public bool Deleted { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<FundTransfer> FundTransfers { get; set; } = new List<FundTransfer>();

    public virtual ICollection<PaymentVoucher> PaymentVouchers { get; set; } = new List<PaymentVoucher>();

    public virtual ICollection<ReceivePayment> ReceivePayments { get; set; } = new List<ReceivePayment>();

    public virtual ICollection<ReceiveVoucher> ReceiveVouchers { get; set; } = new List<ReceiveVoucher>();

    public virtual ICollection<SupplierPayment> SupplierPayments { get; set; } = new List<SupplierPayment>();
}