// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Application.Core.Entities;

public partial class GoodsReceiveNote
{
    public Guid Id { get; set; }

    public string Grnno { get; set; }

    public DateTime Grndate { get; set; }

    public string Ponumber { get; set; }

    public Guid StoreId { get; set; }

    public Guid? CurrencyId { get; set; }

    public Guid SupplierId { get; set; }

    public string ChallanNo { get; set; }

    public DateTime? ChallanDate { get; set; }

    public string TruckNo { get; set; }

    public string DriverName { get; set; }

    public string DriverContactNo { get; set; }

    public int? Transport { get; set; }

    public int PaymentTermInDays { get; set; }

    public int Status { get; set; }

    public string CheckedBy { get; set; }

    public string ApprovedBy { get; set; }

    public string UnpostedBy { get; set; }

    public decimal Subtotal { get; set; }

    public decimal Discount { get; set; }

    public decimal TransportationCost { get; set; }

    public decimal AdditionalLandedCost { get; set; }

    public decimal Total { get; set; }

    public decimal TotalGrnAdjustmentAmount { get; set; }

    public decimal PurchaseOrderTotal { get; set; }

    public bool IsImportPurchase { get; set; }

    public string ProformaInvoiceNo { get; set; }

    public string LcNumber { get; set; }

    public decimal ExchangeRate { get; set; }

    public int ImportPurchaseIncoTerm { get; set; }

    public int ImportPurchasePaymentTerm { get; set; }

    public string PortOfLoading { get; set; }

    public string PortOfDestination { get; set; }

    public string Remark { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime UpdatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public bool Deleted { get; set; }

    public Guid FinancialYearId { get; set; }

    public Guid TenantId { get; set; }

    public bool IsInactive { get; set; }

    public string InactivatedBy { get; set; }

    public virtual ICollection<GoodsReceiveNoteDetail> GoodsReceiveNoteDetails { get; set; } = new List<GoodsReceiveNoteDetail>();

    public virtual Store Store { get; set; }

    public virtual Account Supplier { get; set; }
}