// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Application.Core.Entities;

public partial class LcAdjustment
{
    public Guid Id { get; set; }

    public string Code { get; set; }

    public Guid PurchaseInvoiceId { get; set; }

    public string PurchaseInvoiceNo { get; set; }

    public DateTime AdjustmentDate { get; set; }

    public Guid? CostCenterId { get; set; }

    public decimal InvoiceTotal { get; set; }

    public decimal LcMarginTotal { get; set; }

    public string Remark { get; set; }

    public int Status { get; set; }

    public string CheckedBy { get; set; }

    public string ApprovedBy { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime UpdatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public bool Deleted { get; set; }

    public Guid FinancialYearId { get; set; }

    public Guid TenantId { get; set; }

    public virtual CostCenter CostCenter { get; set; }

    public virtual ICollection<LcAdjustmentDetail> LcAdjustmentDetails { get; set; } = new List<LcAdjustmentDetail>();

    public virtual PurchaseInvoice PurchaseInvoice { get; set; }
}