// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Application.Core.Entities;

public partial class LccostEntryDetail
{
    public Guid Id { get; set; }

    public Guid LccostEntryId { get; set; }

    public Guid DebitAccountId { get; set; }

    public Guid CreditAccountId { get; set; }

    public decimal Amount { get; set; }

    public bool IsIncludedWithinLandedCost { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime UpdatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public bool Deleted { get; set; }

    public Guid TenantId { get; set; }

    public virtual Account CreditAccount { get; set; }

    public virtual Account DebitAccount { get; set; }

    public virtual LccostEntry LccostEntry { get; set; }
}