// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Application.Core.Entities;

public partial class ManufacturingOrderDetail
{
    public Guid Id { get; set; }

    public Guid ManufacturingOrderId { get; set; }

    public Guid RawMaterialId { get; set; }

    public decimal StockQuantity { get; set; }

    public decimal Percentage { get; set; }

    public decimal Quantity { get; set; }

    public decimal Amount { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime UpdatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public bool Deleted { get; set; }

    public Guid TenantId { get; set; }

    public virtual ManufacturingOrder ManufacturingOrder { get; set; }

    public virtual Product RawMaterial { get; set; }
}