// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Application.Core.Entities;

public partial class ManufacturingOrder
{
    public Guid Id { get; set; }

    public string ManufacturingOrderNo { get; set; }

    public string BomNo { get; set; }

    public DateTime ScheduledDate { get; set; }

    public string FormulationNo { get; set; }

    public Guid FinishedProductId { get; set; }

    public int ProductionQuantity { get; set; }

    public Guid RawMaterialStoreId { get; set; }

    public decimal TotalRmused { get; set; }

    public decimal RmCost { get; set; }

    public decimal StandardDirectExpenseAmount { get; set; }

    public decimal StandardFactoryOverheadAmount { get; set; }

    public decimal TotalCost { get; set; }

    public int Status { get; set; }

    public string CheckedBy { get; set; }

    public string ApprovedBy { get; set; }

    public string UnpostedBy { get; set; }

    public string Remark { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime UpdatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public bool Deleted { get; set; }

    public Guid FinancialYearId { get; set; }

    public Guid TenantId { get; set; }

    public bool IsInactive { get; set; }

    public string InactivatedBy { get; set; }

    public virtual Product FinishedProduct { get; set; }

    public virtual ICollection<ManufacturingOrderDetail> ManufacturingOrderDetails { get; set; } = new List<ManufacturingOrderDetail>();

    public virtual Store RawMaterialStore { get; set; }
}