// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Application.Core.Entities;

public partial class Notification
{
    public Guid Id { get; set; }

    public Guid GuidId { get; set; }

    public string Data { get; set; }

    public string Text { get; set; }

    public Guid UserId { get; set; }

    public string Route { get; set; }

    public int Status { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime UpdatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public bool Deleted { get; set; }

    public Guid TenantId { get; set; }
}