// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Application.Core.Entities;

public partial class PoPriceAdjustmentAfterGrn
{
    public Guid Id { get; set; }

    public string Code { get; set; }

    public DateTime AdjustmentDate { get; set; }

    public string ReferenceNo { get; set; }

    public string Grnno { get; set; }

    public string Ponumber { get; set; }

    public Guid SupplierId { get; set; }

    public Guid StoreId { get; set; }

    public decimal TotalAmount { get; set; }

    public string Remark { get; set; }

    public int Status { get; set; }

    public string CheckedBy { get; set; }

    public string ApprovedBy { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime UpdatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public bool Deleted { get; set; }

    public Guid FinancialYearId { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<PoPriceAdjustmentAfterGrnDetail> PoPriceAdjustmentAfterGrnDetails { get; set; } = new List<PoPriceAdjustmentAfterGrnDetail>();

    public virtual Store Store { get; set; }

    public virtual Account Supplier { get; set; }
}