// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Application.Core.Entities;

public partial class PoPriceAdjustmentAfterGrnDetail
{
    public Guid Id { get; set; }

    public Guid PoPriceAdjustmentAfterGrnId { get; set; }

    public Guid ProductId { get; set; }

    public int GrnQuantity { get; set; }

    public decimal GrnRate { get; set; }

    public int AdjustmentQuantity { get; set; }

    public decimal AdjustmentRate { get; set; }

    public decimal Amount { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime UpdatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public bool Deleted { get; set; }

    public Guid TenantId { get; set; }

    public virtual PoPriceAdjustmentAfterGrn PoPriceAdjustmentAfterGrn { get; set; }

    public virtual Product Product { get; set; }
}