// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Application.Core.Entities;

public partial class ProductionDetail
{
    public Guid Id { get; set; }

    public Guid ProductionId { get; set; }

    public Guid RawMaterialId { get; set; }

    public decimal Quantity { get; set; }

    public decimal AdjustmentQuantity { get; set; }

    public decimal AdjustmentValue { get; set; }

    public decimal ActualUsedQuantity { get; set; }

    public decimal Amount { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime UpdatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public bool Deleted { get; set; }

    public Guid TenantId { get; set; }

    public virtual Production Production { get; set; }

    public virtual Product RawMaterial { get; set; }
}