// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Application.Core.Entities;

public partial class Product
{
    public Guid Id { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public string PropertyName { get; set; }

    public Guid InventoryTypeId { get; set; }

    public Guid ProductTypeId { get; set; }

    public Guid? GenericId { get; set; }

    public string Composition { get; set; }

    public Guid? CategoryId { get; set; }

    public Guid? PackSizeId { get; set; }

    public Guid? CountryId { get; set; }

    public bool IsPurchaseProduct { get; set; }

    public bool IsSaleProduct { get; set; }

    public Guid MeasurementUnitId { get; set; }

    public decimal Mrp { get; set; }

    public decimal SalePrice { get; set; }

    public decimal PurchasePrice { get; set; }

    public int AlertQuantity { get; set; }

    public decimal LastPurchaseRate { get; set; }

    public int BagWeight { get; set; }

    public decimal VatPercentage { get; set; }

    public Guid? ManufacturerId { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime UpdatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public bool Deleted { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<BillOfMaterialDetail> BillOfMaterialDetails { get; set; } = new List<BillOfMaterialDetail>();

    public virtual ICollection<BillOfMaterial> BillOfMaterials { get; set; } = new List<BillOfMaterial>();

    public virtual Category Category { get; set; }

    public virtual Country Country { get; set; }

    public virtual ICollection<CustomerWiseProductDiscountDetail> CustomerWiseProductDiscountDetails { get; set; } = new List<CustomerWiseProductDiscountDetail>();

    public virtual ICollection<DeliveryNoteDetail> DeliveryNoteDetails { get; set; } = new List<DeliveryNoteDetail>();

    public virtual ICollection<DiscountProductWiseDetail> DiscountProductWiseDetails { get; set; } = new List<DiscountProductWiseDetail>();

    public virtual Generic Generic { get; set; }

    public virtual ICollection<GoodsReceiveNoteDetail> GoodsReceiveNoteDetails { get; set; } = new List<GoodsReceiveNoteDetail>();

    public virtual InventoryType InventoryType { get; set; }

    public virtual Manufacturer Manufacturer { get; set; }

    public virtual ICollection<ManufacturingOrderDetail> ManufacturingOrderDetails { get; set; } = new List<ManufacturingOrderDetail>();

    public virtual ICollection<ManufacturingOrder> ManufacturingOrders { get; set; } = new List<ManufacturingOrder>();

    public virtual MeasurementUnit MeasurementUnit { get; set; }

    public virtual PackSize PackSize { get; set; }

    public virtual ICollection<PoPriceAdjustmentAfterGrnDetail> PoPriceAdjustmentAfterGrnDetails { get; set; } = new List<PoPriceAdjustmentAfterGrnDetail>();

    public virtual ICollection<ProductCostSetup> ProductCostSetups { get; set; } = new List<ProductCostSetup>();

    public virtual ProductType ProductType { get; set; }

    public virtual ICollection<ProductionDetail> ProductionDetails { get; set; } = new List<ProductionDetail>();

    public virtual ICollection<Production> Productions { get; set; } = new List<Production>();

    public virtual ICollection<PurchaseInvoiceDetail> PurchaseInvoiceDetails { get; set; } = new List<PurchaseInvoiceDetail>();

    public virtual ICollection<PurchaseOrderDetail> PurchaseOrderDetails { get; set; } = new List<PurchaseOrderDetail>();

    public virtual ICollection<PurchaseRequisitionDetail> PurchaseRequisitionDetails { get; set; } = new List<PurchaseRequisitionDetail>();

    public virtual ICollection<PurchaseRequisitionPurchaseOrderMapping> PurchaseRequisitionPurchaseOrderMappings { get; set; } = new List<PurchaseRequisitionPurchaseOrderMapping>();

    public virtual ICollection<PurchaseReturnDetail> PurchaseReturnDetails { get; set; } = new List<PurchaseReturnDetail>();

    public virtual ICollection<SaleInvoiceDetail> SaleInvoiceDetails { get; set; } = new List<SaleInvoiceDetail>();

    public virtual ICollection<SaleOrderDetail> SaleOrderDetails { get; set; } = new List<SaleOrderDetail>();

    public virtual ICollection<SaleQuotationDetail> SaleQuotationDetails { get; set; } = new List<SaleQuotationDetail>();

    public virtual ICollection<SaleReturnDetail> SaleReturnDetails { get; set; } = new List<SaleReturnDetail>();

    public virtual ICollection<StockAdjustmentDetail> StockAdjustmentDetails { get; set; } = new List<StockAdjustmentDetail>();

    public virtual ICollection<StockTransferDetail> StockTransferDetails { get; set; } = new List<StockTransferDetail>();

    public virtual ICollection<Stock> Stocks { get; set; } = new List<Stock>();

    public virtual ICollection<VendorQuotationDetail> VendorQuotationDetails { get; set; } = new List<VendorQuotationDetail>();
}