// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Application.Core.Entities;

public partial class ProductAudit
{
    public Guid ProductId { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public string PropertyName { get; set; }

    public Guid InventoryTypeId { get; set; }

    public Guid ProductTypeId { get; set; }

    public Guid? GenericId { get; set; }

    public string Composition { get; set; }

    public Guid? CategoryId { get; set; }

    public Guid? PackSizeId { get; set; }

    public Guid? CountryId { get; set; }

    public bool IsPurchaseProduct { get; set; }

    public bool IsSaleProduct { get; set; }

    public Guid MeasurementUnitId { get; set; }

    public decimal Mrp { get; set; }

    public decimal SalePrice { get; set; }

    public decimal PurchasePrice { get; set; }

    public int AlertQuantity { get; set; }

    public decimal LastPurchaseRate { get; set; }

    public int BagWeight { get; set; }

    public decimal VatPercentage { get; set; }

    public Guid? ManufacturerId { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime UpdatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public bool DeletedHistory { get; set; }

    public Guid TenantId { get; set; }

    public string ActionType { get; set; }

    public DateTime? ActionDate { get; set; }

    public int Id { get; set; }

    public virtual Category Category { get; set; }

    public virtual Country Country { get; set; }

    public virtual Generic Generic { get; set; }

    public virtual InventoryType InventoryType { get; set; }

    public virtual Manufacturer Manufacturer { get; set; }

    public virtual MeasurementUnit MeasurementUnit { get; set; }

    public virtual PackSize PackSize { get; set; }

    public virtual ProductType ProductType { get; set; }
}