// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Application.Core.Entities;

public partial class PurchaseReturnDetail
{
    public Guid Id { get; set; }

    public Guid PurchaseReturnId { get; set; }

    public Guid ProductId { get; set; }

    public int Grnquantity { get; set; }

    public int GrnBagWeightDeductionQty { get; set; }

    public int Quantity { get; set; }

    public int BagWeightDeductionQty { get; set; }

    public int NumberOfBagQuantity { get; set; }

    public int NetQuantity { get; set; }

    public decimal Rate { get; set; }

    public decimal Amount { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime UpdatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public bool Deleted { get; set; }

    public Guid TenantId { get; set; }

    public virtual Product Product { get; set; }

    public virtual PurchaseReturn PurchaseReturn { get; set; }
}