// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Application.Core.Entities;

public partial class PurchaseInvoice
{
    public Guid Id { get; set; }

    public string PurchaseInvoiceNo { get; set; }

    public DateTime InvoiceDate { get; set; }

    public string Grnno { get; set; }

    public string Ponumber { get; set; }

    public Guid? CurrencyId { get; set; }

    public Guid StoreId { get; set; }

    public Guid SupplierId { get; set; }

    public string SupplierInvoiceNo { get; set; }

    public DateTime? SupplierInvoiceDate { get; set; }

    public int PaymentTermInDays { get; set; }

    public int Status { get; set; }

    public string CheckedBy { get; set; }

    public string ApprovedBy { get; set; }

    public string UnpostedBy { get; set; }

    public decimal Subtotal { get; set; }

    public decimal Discount { get; set; }

    public decimal TransportationCost { get; set; }

    public decimal TotalVat { get; set; }

    public decimal Total { get; set; }

    public string SupplierPaymentCode { get; set; }

    public decimal AdvancePaymentAmount { get; set; }

    public decimal TotalGrnAdjustmentAmount { get; set; }

    public decimal PurchaseOrderTotal { get; set; }

    public decimal NetPayable { get; set; }

    public decimal PaidAmount { get; set; }

    public bool IsImportPurchase { get; set; }

    public string ProformaInvoiceNo { get; set; }

    public string LcNumber { get; set; }

    public decimal ExchangeRate { get; set; }

    public int ImportPurchaseIncoTerm { get; set; }

    public int ImportPurchasePaymentTerm { get; set; }

    public string BillOfEntryNo { get; set; }

    public DateTime? BillOfEntryDate { get; set; }

    public string PortOfLoading { get; set; }

    public string PortOfDestination { get; set; }

    public decimal AdditionalLandedCost { get; set; }

    public decimal AdjustmentValue { get; set; }

    public bool IsLcAdjusted { get; set; }

    public string Remark { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime UpdatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public bool Deleted { get; set; }

    public Guid FinancialYearId { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<LcAdjustment> LcAdjustments { get; set; } = new List<LcAdjustment>();

    public virtual ICollection<PurchaseInvoiceDetail> PurchaseInvoiceDetails { get; set; } = new List<PurchaseInvoiceDetail>();

    public virtual Store Store { get; set; }

    public virtual Account Supplier { get; set; }

    public virtual ICollection<SupplierPaymentAgainstPurchase> SupplierPaymentAgainstPurchases { get; set; } = new List<SupplierPaymentAgainstPurchase>();
}