// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Application.Core.Entities;

public partial class PurchaseRequisition
{
    public Guid Id { get; set; }

    public string RequisitionNo { get; set; }

    public DateTime RequisitionDate { get; set; }

    public Guid StoreId { get; set; }

    public Guid DepartmentId { get; set; }

    public decimal TotalAmount { get; set; }

    public DateTime? ExpectedDeliveryDate { get; set; }

    public string RequestBy { get; set; }

    public int Priority { get; set; }

    public int PaymentTermInDays { get; set; }

    public int Transport { get; set; }

    public int PaymentMode { get; set; }

    public string TermAndCondition { get; set; }

    public Guid? CurrencyId { get; set; }

    public int ImportPurchaseIncoTerm { get; set; }

    public int ImportPurchasePaymentTerm { get; set; }

    public string Remark { get; set; }

    public int RequisitionStatus { get; set; }

    public string CheckedBy { get; set; }

    public string ApprovedBy { get; set; }

    public string UnpostedBy { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime UpdatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public bool Deleted { get; set; }

    public Guid FinancialYearId { get; set; }

    public Guid TenantId { get; set; }

    public virtual Department Department { get; set; }

    public virtual ICollection<PurchaseRequisitionDetail> PurchaseRequisitionDetails { get; set; } = new List<PurchaseRequisitionDetail>();

    public virtual ICollection<RfqSent> RfqSents { get; set; } = new List<RfqSent>();

    public virtual Store Store { get; set; }
}