// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Application.Core.Entities;

public partial class PurchaseOrder
{
    public Guid Id { get; set; }

    public string RequisitionNo { get; set; }

    public string QuotationNo { get; set; }

    public string ReferenceNo { get; set; }

    public string Ponumber { get; set; }

    public DateTime Podate { get; set; }

    public Guid? DeliveryPlaceId { get; set; }

    public Guid? PaymentMethodId { get; set; }

    public Guid StoreId { get; set; }

    public Guid SupplierId { get; set; }

    public string ProductOrigin { get; set; }

    public string PackagingType { get; set; }

    public string ExpiryTime { get; set; }

    public int Transport { get; set; }

    public int PaymentTermInDays { get; set; }

    public int DeliveryTermInDays { get; set; }

    public DateTime DeliveryDate { get; set; }

    public bool IsPartialDelivery { get; set; }

    public int PaymentMode { get; set; }

    public int Status { get; set; }

    public string CheckedBy { get; set; }

    public string ApprovedBy { get; set; }

    public decimal WeightVariance { get; set; }

    public decimal Subtotal { get; set; }

    public decimal Discount { get; set; }

    public decimal Total { get; set; }

    public string TermAndCondition { get; set; }

    public bool IsImportPurchase { get; set; }

    public string ProformaInvoiceNo { get; set; }

    public string LcNumber { get; set; }

    public decimal ExchangeRate { get; set; }

    public Guid? CurrencyId { get; set; }

    public int ImportPurchaseIncoTerm { get; set; }

    public int ImportPurchasePaymentTerm { get; set; }

    public string PortOfLoading { get; set; }

    public string PortOfDestination { get; set; }

    public decimal AdditionalLandedCost { get; set; }

    public string Remark { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime UpdatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public bool Deleted { get; set; }

    public Guid FinancialYearId { get; set; }

    public Guid TenantId { get; set; }

    public bool IsInactive { get; set; }

    public string InactivatedBy { get; set; }

    public virtual DeliveryPlace DeliveryPlace { get; set; }

    public virtual ICollection<LccostEntry> LccostEntries { get; set; } = new List<LccostEntry>();

    public virtual ICollection<PurchaseOrderDetail> PurchaseOrderDetails { get; set; } = new List<PurchaseOrderDetail>();

    public virtual ICollection<PurchaseRequisitionPurchaseOrderMapping> PurchaseRequisitionPurchaseOrderMappings { get; set; } = new List<PurchaseRequisitionPurchaseOrderMapping>();

    public virtual Store Store { get; set; }

    public virtual Account Supplier { get; set; }

    public virtual ICollection<SupplierTransactionAgainstPo> SupplierTransactionAgainstPos { get; set; } = new List<SupplierTransactionAgainstPo>();
}