// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Application.Core.Entities;

public partial class ReceiveVoucher
{
    public Guid Id { get; set; }

    public string VoucherNo { get; set; }

    public DateTime VoucherDate { get; set; }

    public Guid? FundTransferTransactionTypeId { get; set; }

    public string TransactionNumber { get; set; }

    public Guid CostCenterId { get; set; }

    public Guid PaymentModeId { get; set; }

    public string ReferenceNo { get; set; }

    public Guid CashBankAccountId { get; set; }

    public decimal TotalAmount { get; set; }

    public int Status { get; set; }

    public string CheckedBy { get; set; }

    public string ApprovedBy { get; set; }

    public string Remark { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime UpdatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public bool Deleted { get; set; }

    public Guid FinancialYearId { get; set; }

    public Guid TenantId { get; set; }

    public virtual Account CashBankAccount { get; set; }

    public virtual CostCenter CostCenter { get; set; }

    public virtual FundTransferTransactionType FundTransferTransactionType { get; set; }

    public virtual PaymentMode PaymentMode { get; set; }

    public virtual ICollection<ReceiveVoucherDetail> ReceiveVoucherDetails { get; set; } = new List<ReceiveVoucherDetail>();
}