// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Application.Core.Entities;

public partial class SaleQuotationDetail
{
    public Guid Id { get; set; }

    public Guid SaleQuotationId { get; set; }

    public Guid ProductId { get; set; }

    public int BagWeight { get; set; }

    public int PrimaryQuantity { get; set; }

    public int Quantity { get; set; }

    public decimal Rate { get; set; }

    public decimal DiscountPerUnit { get; set; }

    public decimal DiscountAmount { get; set; }

    public decimal Amount { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime UpdatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public bool Deleted { get; set; }

    public Guid TenantId { get; set; }

    public virtual Product Product { get; set; }

    public virtual SaleQuotation SaleQuotation { get; set; }
}