// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Application.Core.Entities;

public partial class SaleReturnDetail
{
    public Guid Id { get; set; }

    public Guid SaleReturnId { get; set; }

    public Guid ProductId { get; set; }

    public int BagWeight { get; set; }

    public int PrimaryQuantity { get; set; }

    public int Quantity { get; set; }

    public int PrimaryBonusQuantity { get; set; }

    public int BonusQuantity { get; set; }

    public decimal Rate { get; set; }

    public int ReturnPrimaryQuantity { get; set; }

    public int ReturnQuantity { get; set; }

    public int ReturnPrimaryBonusQuantity { get; set; }

    public int ReturnBonusQuantity { get; set; }

    public decimal Amount { get; set; }

    public decimal MonthlyDiscountPerUnit { get; set; }

    public decimal YearlyDiscountPerUnit { get; set; }

    public decimal TargetDiscountPerUnit { get; set; }

    public decimal DiscountPercentage { get; set; }

    public decimal PercentageDiscountAmount { get; set; }

    public decimal OtherDiscountPerUnit { get; set; }

    public decimal VatPercentage { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime UpdatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public bool Deleted { get; set; }

    public Guid TenantId { get; set; }

    public virtual Product Product { get; set; }

    public virtual SaleReturn SaleReturn { get; set; }
}