// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Application.Core.Entities;

public partial class SaleReturn
{
    public Guid Id { get; set; }

    public string DeliveryNoteNo { get; set; }

    public string InvoiceNo { get; set; }

    public string SaleReturnNo { get; set; }

    public DateTime SaleReturnDate { get; set; }

    public string ReferenceNo { get; set; }

    public Guid StoreId { get; set; }

    public Guid CustomerId { get; set; }

    public Guid? CustomerMarketingOfficerId { get; set; }

    public Guid? CustomerTerritoryId { get; set; }

    public decimal TotalVat { get; set; }

    public decimal Subtotal { get; set; }

    public decimal TotalPercentageDiscountAmount { get; set; }

    public decimal OtherDiscount { get; set; }

    public decimal Total { get; set; }

    public string Remark { get; set; }

    public int Status { get; set; }

    public string CheckedBy { get; set; }

    public string ApprovedBy { get; set; }

    public string UnpostedBy { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime UpdatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public bool Deleted { get; set; }

    public Guid FinancialYearId { get; set; }

    public Guid TenantId { get; set; }

    public bool IsInactive { get; set; }

    public string InactivatedBy { get; set; }

    public virtual Account Customer { get; set; }

    public virtual Territory CustomerTerritory { get; set; }

    public virtual ICollection<SaleReturnDetail> SaleReturnDetails { get; set; } = new List<SaleReturnDetail>();

    public virtual Store Store { get; set; }
}