// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Application.Core.Entities;

public partial class SaleOrder
{
    public Guid Id { get; set; }

    public string SaleOrderNo { get; set; }

    public string QuotationNo { get; set; }

    public int Transport { get; set; }

    public DateTime OrderDate { get; set; }

    public Guid CustomerId { get; set; }

    public Guid? CustomerMarketingOfficerId { get; set; }

    public decimal CreditLimit { get; set; }

    public decimal LimitAvailed { get; set; }

    public DateTime DeliveryDate { get; set; }

    public string ReferenceNo { get; set; }

    public Guid StoreId { get; set; }

    public decimal Subtotal { get; set; }

    public decimal Discount { get; set; }

    public decimal TotalPercentageDiscountAmount { get; set; }

    public decimal OfferDiscount { get; set; }

    public decimal OtherDiscount { get; set; }

    public decimal Total { get; set; }

    public decimal NetTotal { get; set; }

    public decimal TransportationCost { get; set; }

    public decimal DepoCharge { get; set; }

    public bool IsMailSent { get; set; }

    public string MoneyReceiptNo { get; set; }

    public string Remark { get; set; }

    public int PaymentTerm { get; set; }

    public Guid? CustomerTerritoryId { get; set; }

    public int Status { get; set; }

    public string CheckedBy { get; set; }

    public string ApprovedBy { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime UpdatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public bool Deleted { get; set; }

    public Guid FinancialYearId { get; set; }

    public Guid TenantId { get; set; }

    public virtual Account Customer { get; set; }

    public virtual Territory CustomerTerritory { get; set; }

    public virtual ICollection<CustomerWiseProductDiscountUsageHistory> CustomerWiseProductDiscountUsageHistories { get; set; } = new List<CustomerWiseProductDiscountUsageHistory>();

    public virtual ICollection<DiscountProductWiseUsageHistory> DiscountProductWiseUsageHistories { get; set; } = new List<DiscountProductWiseUsageHistory>();

    public virtual ICollection<SaleOrderDetail> SaleOrderDetails { get; set; } = new List<SaleOrderDetail>();

    public virtual Store Store { get; set; }
}