// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Application.Core.Entities;

public partial class SaleInvoiceDetail
{
    public Guid Id { get; set; }

    public Guid SaleInvoiceId { get; set; }

    public Guid? SaleOrderDetailId { get; set; }

    public Guid ProductId { get; set; }

    public int PrimaryQuantity { get; set; }

    public int PrimaryBonusQuantity { get; set; }

    public int Quantity { get; set; }

    public int BonusQuantity { get; set; }

    public int ReturnQuantity { get; set; }

    public decimal Rate { get; set; }

    public decimal NetRate { get; set; }

    public decimal DiscountPerUnit { get; set; }

    public decimal OfferDiscountPerUnit { get; set; }

    public decimal DiscountAmount { get; set; }

    public decimal InvoiceDiscountPerUnit { get; set; }

    public decimal CashDiscountPerUnit { get; set; }

    public decimal SpecialDiscountPerUnit { get; set; }

    public decimal MonthlyDiscountPerUnit { get; set; }

    public decimal YearlyDiscountPerUnit { get; set; }

    public decimal TargetDiscountPerUnit { get; set; }

    public decimal Amount { get; set; }

    public decimal ReturnAmount { get; set; }

    public string DeliveryNoteNo { get; set; }

    public DateTime? DeliveryDate { get; set; }

    public string DeliveryPlace { get; set; }

    public decimal OtherDiscountPerUnit { get; set; }

    public decimal TransportationCostPerUnit { get; set; }

    public decimal DepoChargePerUnit { get; set; }

    public decimal DiscountPercentage { get; set; }

    public decimal PercentageDiscountAmount { get; set; }

    public decimal VatPercentage { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime UpdatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public bool Deleted { get; set; }

    public Guid TenantId { get; set; }

    public decimal AdjustmentAmount { get; set; }

    public int AdjustmentBonusQuantity { get; set; }

    public decimal AdjustmentPercentageDiscountAmount { get; set; }

    public int AdjustmentQuantity { get; set; }

    public decimal StockIssueCogs { get; set; }

    public virtual Product Product { get; set; }

    public virtual SaleInvoice SaleInvoice { get; set; }
}