// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Application.Core.Entities;

public partial class SaleQuotation
{
    public Guid Id { get; set; }

    public string QuotationNo { get; set; }

    public DateTime QuotationDate { get; set; }

    public Guid CustomerId { get; set; }

    public string ReferenceNo { get; set; }

    public DateTime ExpiryDate { get; set; }

    public string TermAndCondition { get; set; }

    public decimal Subtotal { get; set; }

    public decimal Discount { get; set; }

    public decimal Total { get; set; }

    public bool IsMailSent { get; set; }

    public int Status { get; set; }

    public string CheckedBy { get; set; }

    public string ApprovedBy { get; set; }

    public string Remark { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime UpdatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public bool Deleted { get; set; }

    public Guid FinancialYearId { get; set; }

    public Guid TenantId { get; set; }

    public bool IsInactive { get; set; }

    public string InactivatedBy { get; set; }

    public virtual Account Customer { get; set; }

    public virtual ICollection<SaleQuotationDetail> SaleQuotationDetails { get; set; } = new List<SaleQuotationDetail>();
}