// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Application.Core.Entities;

public partial class StockAdjustmentDetail
{
    public Guid Id { get; set; }

    public Guid StockAdjustmentId { get; set; }

    public Guid ProductId { get; set; }

    public decimal AdjustmentQty { get; set; }

    public decimal AdjustmentValue { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime UpdatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public bool Deleted { get; set; }

    public Guid TenantId { get; set; }

    public virtual Product Product { get; set; }

    public virtual StockAdjustment StockAdjustment { get; set; }
}