// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Application.Core.Entities;

public partial class Stock
{
    public Guid Id { get; set; }

    public int TransactonType { get; set; }

    public Guid InventoryTypeId { get; set; }

    public Guid ProductTypeId { get; set; }

    public Guid ProductId { get; set; }

    public Guid? SupplierId { get; set; }

    public Guid StoreId { get; set; }

    public decimal AvailableQty { get; set; }

    public decimal InQty { get; set; }

    public decimal OutQty { get; set; }

    public decimal InRate { get; set; }

    public decimal InTransportCost { get; set; }

    public decimal OutRate { get; set; }

    public string BatchNo { get; set; }

    public Guid TransactionId { get; set; }

    public DateTime StockInDate { get; set; }

    public DateTime TransactionDate { get; set; }

    public bool IsConsumedInProduction { get; set; }

    public bool IsUnpostedEntry { get; set; }

    public string Remark { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime UpdatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public bool Deleted { get; set; }

    public Guid FinancialYearId { get; set; }

    public Guid TenantId { get; set; }

    public virtual Product Product { get; set; }

    public virtual Store Store { get; set; }
}