// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Application.Core.Entities;

public partial class StockTransfer
{
    public Guid Id { get; set; }

    public string TransferNo { get; set; }

    public DateTime TransferDate { get; set; }

    public Guid SourceId { get; set; }

    public Guid DestinationId { get; set; }

    public string TruckNo { get; set; }

    public int Status { get; set; }

    public string CheckedBy { get; set; }

    public string ApprovedBy { get; set; }

    public string Remark { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime UpdatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public bool Deleted { get; set; }

    public Guid FinancialYearId { get; set; }

    public Guid TenantId { get; set; }

    public bool IsInactive { get; set; }

    public string InactivatedBy { get; set; }

    public virtual Store Destination { get; set; }

    public virtual Store Source { get; set; }

    public virtual ICollection<StockTransferDetail> StockTransferDetails { get; set; } = new List<StockTransferDetail>();
}