// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Application.Core.Entities;

public partial class Store
{
    public Guid Id { get; set; }

    public string Code { get; set; }

    public Guid InventoryTypeId { get; set; }

    public string Name { get; set; }

    public decimal DepoChargePerKg { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime UpdatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public bool Deleted { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<DeliveryNote> DeliveryNotes { get; set; } = new List<DeliveryNote>();

    public virtual ICollection<GoodsReceiveNote> GoodsReceiveNotes { get; set; } = new List<GoodsReceiveNote>();

    public virtual InventoryType InventoryType { get; set; }

    public virtual ICollection<ManufacturingOrder> ManufacturingOrders { get; set; } = new List<ManufacturingOrder>();

    public virtual ICollection<PoPriceAdjustmentAfterGrn> PoPriceAdjustmentAfterGrns { get; set; } = new List<PoPriceAdjustmentAfterGrn>();

    public virtual ICollection<Production> Productions { get; set; } = new List<Production>();

    public virtual ICollection<PurchaseInvoice> PurchaseInvoices { get; set; } = new List<PurchaseInvoice>();

    public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; } = new List<PurchaseOrder>();

    public virtual ICollection<PurchaseRequisition> PurchaseRequisitions { get; set; } = new List<PurchaseRequisition>();

    public virtual ICollection<PurchaseReturn> PurchaseReturns { get; set; } = new List<PurchaseReturn>();

    public virtual ICollection<SaleInvoice> SaleInvoices { get; set; } = new List<SaleInvoice>();

    public virtual ICollection<SaleOrder> SaleOrders { get; set; } = new List<SaleOrder>();

    public virtual ICollection<SaleReturn> SaleReturns { get; set; } = new List<SaleReturn>();

    public virtual ICollection<StockAdjustment> StockAdjustments { get; set; } = new List<StockAdjustment>();

    public virtual ICollection<StockTransfer> StockTransferDestinations { get; set; } = new List<StockTransfer>();

    public virtual ICollection<StockTransfer> StockTransferSources { get; set; } = new List<StockTransfer>();

    public virtual ICollection<Stock> Stocks { get; set; } = new List<Stock>();
}