// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Application.Core.Entities;

public partial class SupplierPaymentAgainstPurchase
{
    public Guid Id { get; set; }

    public string Code { get; set; }

    public DateTime PaymentDate { get; set; }

    public Guid PurchaseInvoiceId { get; set; }

    public Guid SupplierId { get; set; }

    public decimal Amount { get; set; }

    public Guid CostCenterId { get; set; }

    public Guid FromAccountId { get; set; }

    public int Status { get; set; }

    public string CheckedBy { get; set; }

    public string ApprovedBy { get; set; }

    public string UnpostedBy { get; set; }

    public string Remark { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime UpdatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public bool Deleted { get; set; }

    public Guid FinancialYearId { get; set; }

    public Guid TenantId { get; set; }

    public virtual CostCenter CostCenter { get; set; }

    public virtual Account FromAccount { get; set; }

    public virtual PurchaseInvoice PurchaseInvoice { get; set; }
}