// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Application.Core.Entities;

public partial class SupplierTransactionAgainstPo
{
    public Guid Id { get; set; }

    public Guid TransactionId { get; set; }

    public DateTime TransactionDate { get; set; }

    public DateTime? SupplierInvoiceDate { get; set; }

    public int PaymentTermInDays { get; set; }

    public Guid PurchaseOrderId { get; set; }

    public Guid SupplierId { get; set; }

    public int SupplierTransactionType { get; set; }

    public decimal Amount { get; set; }

    public string Remark { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime UpdatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public bool Deleted { get; set; }

    public Guid FinancialYearId { get; set; }

    public Guid TenantId { get; set; }

    public virtual PurchaseOrder PurchaseOrder { get; set; }

    public virtual Account Supplier { get; set; }
}