// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Application.Core.Entities;

public partial class Transaction
{
    public Guid Id { get; set; }

    public Guid FinancialYearId { get; set; }

    public int AccountTransactionType { get; set; }

    public int TransactionQty { get; set; }

    public decimal TransactionQtyValue { get; set; }

    public Guid? PaymentModeId { get; set; }

    public Guid? CostCenterId { get; set; }

    public string Vnumber { get; set; }

    public string Description { get; set; }

    public string ContraAccountIds { get; set; }

    public string ContraAccountNames { get; set; }

    public Guid AccountId { get; set; }

    public decimal Debit { get; set; }

    public decimal Credit { get; set; }

    public bool IsOpeningBalance { get; set; }

    public bool IsPreviousYearClosingBalance { get; set; }

    public DateTime TransactionDate { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime UpdatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public bool Deleted { get; set; }

    public Guid TenantId { get; set; }

    public int SaleInvoiceType { get; set; }
}