// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Application.Core.Entities;

public partial class VoucherEntryDetail
{
    public Guid Id { get; set; }

    public Guid VoucherEntryId { get; set; }

    public Guid AccountId { get; set; }

    public string AccountDescription { get; set; }

    public decimal Amount { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime UpdatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public bool Deleted { get; set; }

    public Guid TenantId { get; set; }

    public virtual Account Account { get; set; }

    public virtual VoucherEntry VoucherEntry { get; set; }
}